import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';

const index=readFileSync(new URL('../public/index.html',import.meta.url),'utf8');
const ui=readFileSync(new URL('../public/data-kraken-ui.js',import.meta.url),'utf8');
const css=readFileSync(new URL('../public/data-kraken.css',import.meta.url),'utf8');
const changelogCss=readFileSync(new URL('../public/changelog-ui.css',import.meta.url),'utf8');
const simpleUi=readFileSync(new URL('../public/candidate-simple-ui.js',import.meta.url),'utf8');
const changelog=readFileSync(new URL('../public/changelog-current-v31712.js',import.meta.url),'utf8');
const dashboardWorker=readFileSync(new URL('../src/index-v20.js',import.meta.url),'utf8');
const liveNews=readFileSync(new URL('../public/live-news-fresh-v2.js',import.meta.url),'utf8');
const newsLearningUi=readFileSync(new URL('../public/news-learning-ui.js',import.meta.url),'utf8');
const clickableMarket=readFileSync(new URL('../public/clickable-market-ui-v31712.js',import.meta.url),'utf8');

assert.match(index,/id="dataFlow"/,'dashboard must contain the central data-flow section');
assert.match(index,/id="krakenCore"/,'depot core must be present');
assert.match(index,/id="krakenPageLinks"/,'the whole dashboard must connect to the central data core');
assert.match(index,/id="krakenOrganLinks"/,'the organ field must be connected by visible Kraken arms');
assert.match(index,/id="krakenDecisionPipeline"/,'the active decision pipeline must be visible');
assert.match(index,/id="krakenPlanktonField"/,'news plankton field must be present');
assert.match(index,/id="krakenDecisionVitals"/,'the core must expose score, data, evidence and learned net edge separately');
for(const vital of ['Score','Quality','Evidence','Edge'])assert.match(index,new RegExp(`id="krakenVital${vital}"`),`${vital} decision vital must be present`);
assert.match(index,/id="krakenCompactAll"/,'the user must be able to collapse all organs into an overview');
assert.match(index,/id="krakenExpandAll"/,'the user must be able to open every organ');
assert.match(index,/id="krakenOrganCount"/,'the complete overview must show its connected organ count');
assert.match(index,/class="krakenOnePager"/,'the Kraken must be the default viewport-sized onepager');
assert.match(index,/id="krakenOrganDock"/,'all organs must have a simultaneous onepage dock');
assert.match(index,/id="krakenOrganTiles"/,'the onepage dock must expose live organ tiles');
assert.match(index,/id="krakenNewsTrace"/,'the onepage must expose the live news processing trace');
assert.match(index,/id="krakenNewsTraceItems"/,'incoming news states must have a live target');
assert.match(index,/id="overview" class="heroKpis" aria-hidden="true"/,'the duplicated legacy KPI strip must stay out of the onepage view');
assert.match(index,/So verarbeitet das Markt-System neue Informationen/,'the flow must explain itself without an internal Kraken-center label');
assert.doesNotMatch(index,/Kraken-Zentrum/,'internal Kraken-center wording must not be visible');
assert.match(index,/id="krakenOrganBackdrop"/,'large organ details must open above the onepager');
assert.match(index,/id="krakenDetailPath"/,'the integrated detail must explain its path from data to organ');
assert.match(index,/data-kraken-source="pc"/,'PC scanner must be shown as an input');
assert.match(index,/data-kraken-source="news"/,'news must be shown as an input');
assert.match(index,/data-kraken-ui\.js/,'living UI module must be loaded');
assert.match(index,/data-kraken\.css/,'living UI styles must be loaded');

assert.match(ui,/planspiel:status/,'UI must reuse the existing dashboard status event');
assert.doesNotMatch(ui,/\bfetch\s*\(/,'UI must not add a second status request');
assert.doesNotMatch(ui,/\/api\/status/,'UI must not add Cloudflare status traffic');
for(const phase of ['Sammelt','Prüft','Ordnet','Priorisiert','Wägt','Sortiert','Verwertet']){
  assert.match(ui,new RegExp(phase),`living process must expose the ${phase} phase`);
}
assert.match(ui,/scanFresh/,'animation must distinguish fresh from stale data');
assert.match(ui,/WOCHENENDPAUSE/,'expected weekend downtime must not be shown as an outage');
assert.match(ui,/marketHeaderStatus/,'the legacy market header must agree with the weekend state');
assert.match(ui,/scannerLiveTitle/,'the legacy scanner banner must agree with the weekend state');
assert.match(ui,/newsCatalystPolicy/,'UI must show the news that actually reaches the decision layer');
assert.match(ui,/function renderCommandDeck/,'the top priority and processing chain must be rendered');
assert.match(ui,/function tradeReadiness/,'visible buy readiness must combine score, quality, evidence and net edge');
assert.match(ui,/function compareTradeCandidates/,'visible opportunities must rank tradable readiness before a merely high blocked score');
assert.match(ui,/function candidateLearningEdge/,'learned net edge must be visible instead of hiding behind a raw score');
assert.match(ui,/function latestEvent/,'status histories must select the actually newest timestamp');
assert.match(ui,/config\?\.ai_last_summary/,'the current decision summary must win over old history rows');
assert.doesNotMatch(ui,/arr\(status\.aiLog\)\.at\(-1\)/,'a newest-first log must not show its oldest BUY as current');
assert.match(ui,/function renderPlankton/,'news must drive the plankton visualization');
assert.match(ui,/function renderNewsTrace/,'incoming news must expose its processing state');
assert.doesNotMatch(ui,/\$\{watchCount\} Katalysatoren/,'an empty forward pool must not pretend the complete macro/news path has zero catalysts');
assert.match(ui,/const ESSENTIAL_ORGANS=/,'the onepager must define a deliberately reduced function set');
assert.doesNotMatch(ui,/Die Krake hebt/,'status refreshes must not restore removed internal naming');
assert.match(ui,/function setOrganExpanded/,'every dashboard organ must be independently expandable');
assert.match(ui,/function organSummary/,'collapsed organs must retain a useful live summary');
assert.match(ui,/localStorage\.setItem\(ORGAN_PREF_KEY/,'the chosen organ layout must persist');
assert.match(ui,/newsSamples/,'the bounded news outcome-learning sample count must be visible');
assert.match(ui,/newsLearningTotal/,'the visible 40-row radar must be distinguished from the full news-learning memory');
assert.match(ui,/15 Minuten, 1 Stunde, 4 Stunden und 6 Stunden/,'the UI must explain the actual regional news reaction windows');
assert.match(ui,/decoratePageOrgans/,'the complete dashboard must become part of the data organism');
assert.match(ui,/positionTradeChart.*CHART-AUGE/,'the dynamically created trade chart must become an organ');
assert.match(ui,/newsLearning.*NEWS-GEDÄCHTNIS/,'the dynamically created news learning card must become an organ');
assert.match(ui,/agmCalendarBottom.*TERMINSINN/,'the dynamically created AGM calendar must become an organ');
assert.match(ui,/MutationObserver/,'later UI modules must be discovered automatically');
assert.match(ui,/krakenScannerNerve/,'the scanner status must be inside the connected overview');
assert.match(ui,/KPI_SENSES/,'depot KPIs must be represented as live sensory cells');
assert.match(ui,/EXPANDED_ORGAN_COLUMNS/,'dynamic organs must regain useful widths when opened');
assert.match(ui,/function renderOrganDock/,'all organs must render into the simultaneous onepage overview');
assert.match(ui,/function organAvailability/,'empty organ data must be explained instead of looking broken');
assert.match(ui,/function updateOrganConnection/,'opened organs must expose their real connection state');
assert.match(ui,/querySelector\('\.krakenOrganBadge'\)/,'dynamic refreshes must not duplicate an organ badge');
assert.match(ui,/function openOrganDetail/,'an organ tile must open its full detail without leaving the overview');
assert.match(ui,/function positionOrganDetail/,'organ details must be positioned inside the Kraken stage');
assert.match(ui,/function closeOrganDetail/,'organ details must return directly to the onepage center');
assert.match(ui,/function concealOnePagerOrgans/,'legacy inline display rules must not leak hidden charts into the onepager');
assert.match(ui,/attributeFilter:\['style'\]/,'late inline chart visibility changes must be observed and corrected');
assert.match(ui,/event\.key==='Escape'/,'Escape must close an open organ detail');
assert.match(ui,/drawPageLinks/,'the dashboard organs must be connected visually');
assert.match(ui,/function drawOrganLinks/,'the depot core must draw a live arm to every organ');
assert.match(ui,/function scheduleGeometryDraw/,'large SVG geometry updates must be coalesced into one browser frame');
assert.doesNotMatch(ui,/setInterval\(updateThought/,'the living thought loop must not wake a hidden or idle dashboard continuously');
assert.match(ui,/document\.hidden&&latestStatus&&scanFresh/,'thought animation must only advance in a visible tab with fresh scanner data');
assert.match(ui,/krakenUiIdle/,'stale and weekend states must pause expensive motion');
assert.match(ui,/data-organ-link/,'each organ arm must retain the identity of its endpoint');
assert.match(ui,/normalizedScore\(b\)-normalizedScore\(a\)/,'focus stocks must be sorted strongest first');
assert.match(ui,/normalizedScore\(candidate\)>=50/,'weak candidates must not be pulled into the foreground');
assert.match(ui,/held\.has/,'held positions must not duplicate the opportunity focus');
assert.doesNotMatch(simpleUi,/manual-trade-ui/,'manual buy and sell controls must not be loaded');

assert.match(css,/@keyframes krakenFlow/,'data arms must visibly flow');
assert.match(css,/@keyframes corePulse/,'depot core must pulse');
assert.match(css,/@keyframes newsFly/,'fresh news must visibly fly into processing');
assert.match(css,/@keyframes planktonIn/,'news plankton must flow into the depot core');
assert.match(css,/\.krakenDecisionPipeline/,'decision processing must be legible');
assert.match(css,/\.krakenOrgan\.organCollapsed/,'the complete dashboard must support a compact organ overview');
assert.match(css,/\.krakenOrganToggle/,'organ expand controls must be styled consistently');
assert.match(css,/prefers-reduced-motion/,'all living UI motion must respect reduced-motion preferences');
assert.match(css,/\.krakenOrgan/,'dashboard cards must be styled as connected organs');
assert.match(css,/#newsLearning[^}]*\.krakenOrgan\{display:block!important\}/,'legacy rescue CSS must not hide the connected news-learning organ');
assert.match(css,/html\.krakenOnePager,body\.krakenOnePager\{height:100%;overflow:hidden!important\}/,'the main Kraken onepager must not create page scrolling');
assert.match(css,/\.krakenOrganTiles\{position:relative!important;display:block!important/,'essential functions must float freely instead of forming a list');
assert.match(css,/\.krakenOrgan\.organFocused\{position:fixed!important/,'opened organs must use a viewport detail layer');
assert.match(css,/\.krakenNewsTrace/,'the live news processing trace must be styled');
assert.match(css,/\.manualV307\{display:none!important\}/,'legacy manual trading controls must stay hidden');
assert.match(css,/@keyframes tileSignalSweep/,'new information must visibly travel through active organ tiles');
assert.match(css,/\.krakenOrganConnection/,'opened organs must explain live, waiting and protected states');
assert.match(css,/@keyframes organBloom/,'an opened organ must visibly grow from the Kraken diagram');
assert.match(css,/\.krakenOrganLinks \.organTissue/,'the decision core must expose organic tissue toward every essential function');
assert.match(css,/\.krakenOrganLinks \.organArm/,'each organ must have a colored branch');
assert.match(css,/@keyframes organArmFlow/,'information must visibly flow along the organ branches');
assert.match(css,/krakenOrganDetailOpen #livePanel>\.dashboardGrid\{z-index:202!important\}/,'opened organ content must paint above its integrated backdrop');
assert.match(css,/@keyframes pageTentacleFlow/,'page-wide data arms must flow');
assert.match(css,/\.krakenStage\.is-stale/,'stale status must slow or stop activity');
assert.match(css,/V31\.7\.25: fluessiger Organismus/,'the performance policy must be documented beside the animation rules');
assert.match(css,/krakenPerformanceMode \.krakenPageLinks path[^}]*animation:none!important/,'passive page-wide paths must not animate continuously');
assert.match(css,/krakenPerformanceMode \.krakenOrganLinks path[^}]*animation:none!important/,'passive organ arms must not animate continuously');
assert.match(css,/krakenPerformanceMode\.krakenUiPaused/,'hidden tabs must pause all Kraken animation work');
assert.match(css,/@container \(max-width:620px\)/,'visualization must remain usable on mobile');
assert.match(css,/\.krakenNode b\{font-size:13px!important\}/,'desktop source names must no longer use microscopic type');
assert.match(css,/\.krakenNewsTraceItem b\{font-size:10px!important\}/,'desktop news text must remain readable');
assert.match(css,/\.krakenOrganTile \.krakenOrganTileCopy>b\{font-size:15px!important/,'desktop function names must remain readable');
assert.match(css,/V31\.7\.21: Handy ist kein verkleinerter Desktop/,'mobile onepager must have its own deliberate layout');
assert.match(css,/\.krakenInputs\{display:grid!important[^}]*grid-template-columns:repeat\(4/,'all four real data sources must remain visible on mobile');
assert.match(css,/\.krakenOrganTile \.krakenOrganTileCopy>b\{font-size:12\.5px!important/,'mobile function names must not use microscopic type');
assert.match(css,/\.krakenNewsTraceItem b\{font-size:10\.5px!important/,'mobile incoming news must remain readable');
assert.match(css,/\.krakenOrganTile em\{right:5px!important;width:22px!important;height:22px!important/,'mobile function detail controls must remain tappable');
assert.match(css,/V31\.7\.22: Der Depotkern zeigt/,'the decision-vitals visualization must be documented in CSS');
assert.match(css,/\.krakenDecisionVitals\{position:relative;display:grid;grid-template-columns:repeat\(4/,'the four decision vitals must form one compact visual unit');
assert.match(css,/data-kraken-source="charts"\].*display:none!important/,'redundant processing inputs must stay hidden on mobile so the four real sources fit');
assert.match(css,/@media\(min-width:1600px\)/,'ultra-wide desktops must receive a readable scale instead of microscopic labels');
assert.match(css,/@media\(max-width:760px\) and \(max-height:620px\)/,'low landscape phones need a separate onepage arrangement');
assert.match(css,/V31\.7\.24: Desktop und Handy besitzen feste, kollisionsfreie Zonen/,'the overlap correction must stay documented beside the layout rules');
assert.match(css,/\.krakenNewsTrace\{left:20%!important;right:45%!important;width:auto!important/,'desktop news must end before the function dock begins');
assert.match(css,/\.krakenOrganDock\{left:57%!important;right:1%!important;width:auto!important/,'desktop function dock must own a separate non-overlapping zone');
assert.match(changelogCss,/height:100dvh!important/,'mobile changelog must fill the phone viewport');
assert.match(changelogCss,/\.changelogList\{[^}]*overflow-y:auto!important/,'mobile changelog must own its scroll region');
assert.match(changelogCss,/\.changelogEntry li\{[^}]*font-size:14px!important/,'mobile changelog copy must remain readable');
assert.match(changelogCss,/\.changelogClose\{[^}]*width:44px!important;height:44px!important/,'mobile changelog close control must remain reachable');
assert.match(css,/V31\.7\.26: Die doppelte KPI-Leiste entfällt/,'the removed duplicate KPI strip must be documented beside the onepage layout');
assert.match(css,/#overview\{display:none!important\}/,'the duplicate KPI strip must not consume desktop or phone space');
assert.match(liveNews,/function renderStatusFeed/,'News-Impulse must render the actual dashboard radar payload');
assert.match(liveNews,/noExtraFeedRequests:true/,'the news detail must declare status-only rendering');
assert.doesNotMatch(liveNews,/setInterval\(load/,'the news detail must not start another minute polling loop');
assert.doesNotMatch(newsLearningUi,/fetch\('\/api\/status'/,'news learning must reuse the already loaded dashboard status');
assert.doesNotMatch(clickableMarket,/setInterval\(loadLiveNews/,'chart links must not start a competing news polling loop');
assert.match(dashboardWorker,/newsRadarVisible/,'the dashboard must expose its deliberately bounded radar window');
assert.match(dashboardWorker,/newsLearningTotal/,'the dashboard must expose the separate learning-memory count');
assert.match(dashboardWorker,/positionScoreAudit:_positionScoreAudit/,'large score audits must be removed from the routine dashboard payload');
assert.match(dashboardWorker,/audit:_audit,\.\.\.lightProfitExit/,'the duplicated profit-exit audit must be removed from the routine dashboard payload');
assert.match(changelog,/07\.09\.2026 · 09:25/,'regional news-reaction correction must be documented first');
assert.match(changelog,/V31\.7\.26/,'regional news learning and slim dashboard update must be documented');
assert.match(changelog,/V31\.7\.25/,'browser performance correction must remain documented');
assert.match(changelog,/V31\.7\.25/,'coalesced rendering and targeted motion update must be documented');
assert.match(changelog,/V31\.7\.24/,'collision-free UI and preserved news safety update must be documented');
assert.match(changelog,/V31\.7\.23/,'weekend and Trade Republic production validation update must be documented');
assert.match(changelog,/V31\.7\.22/,'cost-aware readiness and responsive UI update must be documented');
assert.match(changelog,/V31\.7\.21/,'mobile readability update must be documented');
assert.match(changelog,/Handy-Prüfung und ein Eintrag ganz oben im Changelog/,'mobile QA and changelog tracking must be a permanent UI rule');
assert.match(changelog,/keine zusätzlichen Cloudflare-Statusaufrufe/,'load behavior must be documented');

console.log('data-kraken-ui tests passed');
