import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const read=p=>readFileSync(new URL(`../${p}`,import.meta.url),'utf8');
const compat=read('public/ui-v283-fix.js');
const ui=read('public/v286-live-ui.js');
const entry=read('src/index-v19.js');
const wrangler=read('wrangler.jsonc');
assert.match(compat,/compatibilityOnly:true/);
assert.match(compat,/scoreRenderer:false/);
assert.match(compat,/V28\.6 · Einheitlicher Score/);
assert.match(compat,/V28\.2 · Relative Opportunity Learning/);
assert.match(compat,/V28\.1 · Research Signal Fusion/);
assert.match(compat,/V28\.0 · Trade Maturity/);
assert.match(compat,/V27\.9 · Opportunity Learning/);
assert.match(ui,/Research \$\{shown\}/);
assert.match(ui,/72\+ Kaufbereit/);
assert.match(ui,/40–57 Aufbau/);
assert.match(ui,/Mo–Fr 07:30–23:00/);
assert.match(ui,/singleScoreRenderer:true/);
assert.match(ui,/cleanupLegacy/);
assert.match(entry,/v286-live-ui\.js/);
assert.match(entry,/quota-guard\.js/);
assert.match(wrangler,/"main"\s*:\s*"src\/index-v20\.js"/);
console.log('V28.6 UI/live integration regression tests: OK');
