import assert from 'node:assert/strict';
import {enforceHeldCashDeploymentV304} from '../src/held-cash-deployment-v304.js';
const verified=(symbol,i)=>({symbol,name:symbol,decisionScore:72-i,momentum5Pct:.1,momentum20Pct:.2,brokerVerified:true,assetClass:'EQUITY',brokerVerificationSource:'official Trade Republic Trading Universe PDF',brokerMatchMode:'EXACT_NORMALIZED_NAME',isin:`DE000000000${i+1}`});
const candidates=['A.DE','B.DE','C.DE','D.DE'].map((s,i)=>verified(s,i));
const positions=candidates.map(c=>({symbol:c.symbol,name:c.name,invested:1500,entry_price:100,last_price:100,entry_fx:1,last_fx:1,decisionScore:c.decisionScore}));
const plan={summary:'hold four',actions:positions.map(p=>({symbol:p.symbol,action:'HOLD',allocation_pct:0,reason:'stable'}))};
const state={config:{cash:4000},positions,candidates};
const out=enforceHeldCashDeploymentV304(structuredClone(plan),state);
const buys=out.plan.actions.filter(a=>a.action==='BUY');
assert.ok(out.counters.topups>=1,'at least the strongest verified holding should be eligible for top-up');
assert.ok(buys.length>=1);
assert.ok(buys.some(a=>a.allocation_pct>25),'V30.7 must no longer clamp a strong holding to the old 25% order/allocation cap');
assert.ok(buys.reduce((s,a)=>s+a.allocation_pct,0)>=94.9,'about 95% of available cash may deploy while leaving the 2% equity reserve');
assert.ok(buys.every(a=>/DYNAMIC CASH-DEPLOYMENT/.test(a.reason)));
const unsafe=structuredClone(state);unsafe.candidates[0].brokerVerified=false;
const out2=enforceHeldCashDeploymentV304(structuredClone(plan),unsafe);
const unsafeBuy=out2.plan.actions.find(a=>a.symbol==='A.DE'&&a.action==='BUY');
assert.equal(unsafeBuy,undefined,'unverified holding must never be topped up');
console.log(JSON.stringify({ok:true,topups:out.counters.topups,maxAllocationPct:Math.max(...buys.map(a=>a.allocation_pct)),unverifiedBlocked:true,noFixed25PctCap:true},null,2));
