import assert from 'node:assert/strict';
import {enforceProfitOpportunityV305,ProfitOpportunityGuardV305} from '../src/profit-opportunity-v305.js';
const tr=(symbol,score)=>({symbol,name:symbol,decisionScore:score,daytradeLiveScore:score,momentum5Pct:.2,momentum20Pct:.25,brokerVerified:true,assetClass:'EQUITY',brokerVerificationSource:'official Trade Republic Trading Universe PDF',brokerMatchMode:'EXACT_NORMALIZED_NAME',isin:'DE0000000001'});
const stripped={symbol:'NEW.DE',name:'NEW.DE',decisionScore:70,daytradeLiveScore:70,momentum5Pct:.2,momentum20Pct:.25};
const verified=tr('NEW.DE',70),input={messages:[{content:`Kandidaten=${JSON.stringify([stripped])} Gehalten=[]`}]};
const stalePlan={summary:'stale',actions:[{symbol:'NEW.DE',action:'HOLD',reason:'TRADE-REPUBLIC-BLOCK: metadata missing in older guard'}]};
const fake={run:async()=>({response:JSON.stringify(stalePlan)})};
const guard=new ProfitOpportunityGuardV305(fake,{getState:()=>({positions:[],candidates:[stripped]}),getBrokerRows:async()=>[verified]});
const result=await guard.run('model',input),plan=JSON.parse(result.response),status=guard.status();
assert.equal(plan.actions[0].action,'BUY','exact official master verification must recover a stale broker-only false negative');
assert.equal(status.patch,'30.5.3');
assert.equal(status.authoritativeBrokerUniverseResolve,true);
assert.equal(status.latest.exactTradeRepublicCandidates,1);
assert.equal(status.latest.staleBrokerBlocksCleared,1);
const hard=enforceProfitOpportunityV305({summary:'hard',actions:[{symbol:'NEW.DE',action:'HOLD',reason:'NEWS-SHOCK: severe negative event'}]},{positions:[],candidates:[verified]},{messages:[{content:`Kandidaten=${JSON.stringify([verified])} Gehalten=[]`}]});
assert.equal(hard.counters.starterBuys,0,'real hard safety must remain absolute');
const unsafe={...verified,brokerVerified:false};
const unsafeOut=enforceProfitOpportunityV305({summary:'unsafe',actions:[{symbol:'NEW.DE',action:'HOLD',reason:'TRADE-REPUBLIC-BLOCK: not verified'}]},{positions:[],candidates:[unsafe]},{messages:[{content:`Kandidaten=${JSON.stringify([unsafe])} Gehalten=[]`}]});
assert.equal(unsafeOut.counters.starterBuys,0,'an actually unverified stock must remain blocked');
console.log(JSON.stringify({ok:true,patch:'30.5.3',staleBrokerFalseNegativeRecovered:true,hardSafetyPreserved:true,unverifiedStillBlocked:true},null,2));
