import assert from 'node:assert/strict';
import {evaluateSellRebuyV306,enforceSellRebuyChurnV306} from '../src/sell-rebuy-churn-v306.js';
const now=Date.parse('2026-08-24T15:20:00Z');
const history=[{symbol:'YIT.HE',action:'VERKAUF',ts:'2026-08-24T15:05:00Z',price:3.199,reason:'normaler Gewinnverkauf'}];
const candidate={symbol:'YIT.HE',decisionScore:66,daytradeLiveScore:66,momentum5Pct:.08,momentum20Pct:.16,acceleration5Pct:.01,price:3.203};
const ev=evaluateSellRebuyV306({history,candidate,action:{symbol:'YIT.HE',action:'BUY',reason:'soft re-entry'},now});
assert.equal(ev.block,true,'YIT-like 15 minute sell->rebuy must be blocked');
assert.equal(ev.rebuyHigher,true,'more expensive rapid rebuy should be recognized');
const plan={summary:'re-entry',actions:[{symbol:'YIT.HE',action:'BUY',allocation_pct:20,reason:'soft re-entry'}]};
const out=enforceSellRebuyChurnV306(structuredClone(plan),{history,candidates:[candidate]},null,now);
assert.equal(out.counters.blockedRapidSellRebuys,1);
assert.equal(out.counters.higherPriceRebuysBlocked,1);
assert.equal(out.plan.actions[0].action,'HOLD');
assert.match(out.plan.actions[0].reason,/SELL→REBUY-CHURN BLOCK/);
const exceptional={...candidate,decisionScore:77,daytradeLiveScore:77,momentum5Pct:.42,momentum20Pct:.72,acceleration5Pct:.06,price:3.215,setup:'BREAKOUT RECLAIM'};
const allowed=evaluateSellRebuyV306({history,candidate:exceptional,action:{symbol:'YIT.HE',action:'BUY',reason:'BREAKOUT RECLAIM after fresh catalyst'},now});
assert.equal(allowed.block,false,'genuinely new exceptional setup after 15m may re-enter');
assert.equal(allowed.exceptional,true);
const tooFast=evaluateSellRebuyV306({history:[{...history[0],ts:'2026-08-24T15:14:00Z'}],candidate:{...exceptional,daytradeLiveScore:73,decisionScore:73,momentum5Pct:.25,momentum20Pct:.4,acceleration5Pct:.03},action:{symbol:'YIT.HE',action:'BUY',reason:'BREAKOUT'},now});
assert.equal(tooFast.block,true,'under 10m requires ultra-strong exception');
const hard=evaluateSellRebuyV306({history:[{...history[0],ts:'2026-08-24T14:40:00Z',reason:'HARD NEWS-SHOCK exit'}],candidate:exceptional,action:{symbol:'YIT.HE',action:'BUY',reason:'BREAKOUT'},now});
assert.equal(hard.block,true,'hard exits stay locked for 120m');
const samePlan=enforceSellRebuyChurnV306({summary:'bad',actions:[{symbol:'ABC.DE',action:'SELL'},{symbol:'ABC.DE',action:'BUY',allocation_pct:10}]},{history:[],candidates:[{symbol:'ABC.DE'}]},null,now);
assert.equal(samePlan.plan.actions.find(x=>x.action==='HOLD')?.sellRebuyChurnBlockedV306,true,'same-cycle sell+buy must be blocked');
console.log(JSON.stringify({ok:true,yitLikeChurnBlocked:true,higherPriceRebuyBlocked:true,exceptionalReentryPreserved:true,absoluteCooldown:true,hardExitCooldown:true,sameCycleFlipBlocked:true},null,2));
