param([string]$Root='E:\KI-Markt-Agent')
$ErrorActionPreference='Stop';$ProgressPreference='SilentlyContinue';$AgentVersion='1.2.0-v28.8';$DefaultServer='https://ki-markt-planspiel.orkimperium.workers.dev';$BerlinTimeZone='W. Europe Standard Time';$Closed2026=@('2026-01-01','2026-04-03','2026-04-06','2026-05-01','2026-12-24','2026-12-25','2026-12-31');$script:DownloadedBytes=0L;$script:UploadedBytes=0L;$script:LastCpu=[double](Get-Process -Id $PID).CPU;$script:LastCpuAt=[DateTime]::UtcNow;$script:LastCleanupAt=$null;$script:LastError=$null
$ConfigPath=Join-Path $Root 'config.json';$TokenPath=Join-Path $Root 'agent-token.txt';$DataRoot=Join-Path $Root 'data';$CacheRoot=Join-Path $DataRoot 'cache';$LogRoot=Join-Path $DataRoot 'logs';New-Item -ItemType Directory -Force -Path $Root,$DataRoot,$CacheRoot,$LogRoot|Out-Null
$cfg=[ordered]@{serverUrl=$DefaultServer;maxStorageGb=2.0;trimToGb=1.6;keepDays=30;pcFirstShardCount=4};if(Test-Path $ConfigPath){try{$loaded=Get-Content $ConfigPath -Raw|ConvertFrom-Json;foreach($n in @('serverUrl','maxStorageGb','trimToGb','keepDays','pcFirstShardCount')){if($null -ne $loaded.$n){$cfg[$n]=$loaded.$n}}}catch{}};$ServerUrl=([string]$cfg.serverUrl).TrimEnd('/');$MaxStorageBytes=[int64]([double]$cfg.maxStorageGb*1GB);$TrimToBytes=[int64]([double]$cfg.trimToGb*1GB);if($TrimToBytes-ge $MaxStorageBytes){$TrimToBytes=[int64]($MaxStorageBytes*.8)}
function Write-AgentLog([string]$Text){Add-Content -Path (Join-Path $LogRoot ("agent-{0}.log" -f (Get-Date -Format 'yyyy-MM-dd'))) -Value "$(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')  $Text" -Encoding UTF8}
function Get-BerlinNow(){return [TimeZoneInfo]::ConvertTimeBySystemTimeZoneId([DateTime]::UtcNow,$BerlinTimeZone)}
function Get-Session([DateTime]$d){$ymd=$d.ToString('yyyy-MM-dd');$m=$d.Hour*60+$d.Minute;$w=$d.DayOfWeek;$t=($w-ne 'Saturday' -and $w-ne 'Sunday' -and $Closed2026 -notcontains $ymd);$pre=$t -and $m-ge 445 -and $m-lt 450;$open=$t -and $m-ge 450 -and $m-lt 1380;[pscustomobject]@{trading=$t;preopen=$pre;open=$open;phase=if($open){'OPEN'}elseif($pre){'PREOPEN'}elseif($t){'CLOSED'}else{'NON_TRADING_DAY'};minute=$m}}
function Get-DataBytes(){$sum=0L;Get-ChildItem $DataRoot -File -Recurse -ErrorAction SilentlyContinue|ForEach-Object{$sum+=$_.Length};return $sum}
function Invoke-LocalCleanup(){$cut=(Get-Date).AddDays(-[double]$cfg.keepDays);Get-ChildItem $DataRoot -File -Recurse -ErrorAction SilentlyContinue|Where-Object{$_.LastWriteTime-lt $cut}|Remove-Item -Force -ErrorAction SilentlyContinue;$script:LastCleanupAt=[DateTime]::UtcNow}
function Get-CpuPercent(){$p=Get-Process -Id $PID;$n=[DateTime]::UtcNow;$e=($n-$script:LastCpuAt).TotalSeconds;$d=[double]$p.CPU-$script:LastCpu;$c=[Math]::Max(1,[Environment]::ProcessorCount);$v=if($e-gt 0){100*$d/$e/$c}else{0};$script:LastCpu=[double]$p.CPU;$script:LastCpuAt=$n;return [Math]::Max(0,[Math]::Min(100,$v))}
function Get-Metrics([string]$Phase){$p=Get-Process -Id $PID;[ordered]@{version=$AgentVersion;hostName=$env:COMPUTERNAME;storagePath=$Root;storageBytes=(Get-DataBytes);maxStorageBytes=$MaxStorageBytes;cpuPct=[Math]::Round((Get-CpuPercent),2);ramMb=[Math]::Round($p.WorkingSet64/1MB,1);downloadedBytes=$script:DownloadedBytes;uploadedBytes=$script:UploadedBytes;localPhase=$Phase;agentMode='PC_FIRST_FULL_UNIVERSE_V288';lastError=$script:LastError}}
function Invoke-TrackedGet([string]$Url){$r=Invoke-WebRequest -Uri $Url -UseBasicParsing -TimeoutSec 8 -Headers @{'User-Agent'='Mozilla/5.0 KI-Markt-Agent/1.2';'Accept'='application/json,text/html'};$t=[string]$r.Content;$script:DownloadedBytes+=[Text.Encoding]::UTF8.GetByteCount($t);return $t}
function Invoke-AgentPost([string]$Path,$Body){$token=(Get-Content $TokenPath -Raw).Trim();if(-not $token){throw 'agent-token.txt ist leer.'};$j=$Body|ConvertTo-Json -Depth 12 -Compress;$script:UploadedBytes+=[Text.Encoding]::UTF8.GetByteCount($j);Invoke-RestMethod -Uri ($ServerUrl+$Path) -Method Post -ContentType 'application/json' -Headers @{Authorization="Bearer $token"} -Body $j -TimeoutSec 60}
$module=Join-Path $Root 'pc-first-scanner.ps1';if(-not(Test-Path $module)){throw "$module fehlt."};. $module;if([int]$cfg.pcFirstShardCount-ge 2 -and [int]$cfg.pcFirstShardCount-le 12){$script:PcFirstShardCount=[int]$cfg.pcFirstShardCount};if(-not(Test-Path $TokenPath)){exit 2};Write-AgentLog "KI-Markt-Agent $AgentVersion gestartet · PC-FIRST Voll-Master."
while($true){try{$session=Get-Session (Get-BerlinNow);if(-not $session.trading -or $session.minute-lt 440 -or $session.minute-ge 1385){Start-Sleep -Seconds 60;continue};$metrics=Get-Metrics $session.phase;if($session.preopen){if($session.minute-eq 445){try{Update-PcFirstUniverse -Force|Out-Null}catch{}};Invoke-AgentPost '/api/agent/heartbeat' $metrics|Out-Null}elseif($session.open){$pc=$null;try{$pc=Invoke-PcFirstPipeline;$prefetch=[ordered]@{leaderUpdatedAt=[DateTime]::UtcNow.ToString('o');leaderEntries=$pc.leaderEntries;pcFirstScan=$pc.summary;metrics=$metrics};Invoke-AgentPost '/api/agent/prefetch' $prefetch|Out-Null;Write-AgentLog ("PC-FIRST: Master {0} · Vorscan {1} ({2}%) · Deep {3} · Final {4}" -f $pc.summary.masterUniverseCount,$pc.summary.prescannedCount,$pc.summary.fullCycleCoveragePct,$pc.summary.deepCount,$pc.summary.finalistCount)}catch{Write-AgentLog "PC-FIRST fehlgeschlagen: $($_.Exception.Message)"};$m=Get-Metrics $session.phase;if($pc){$m.pcFirstVersion=28.8;$m.pcFirstCoveragePct=$pc.summary.fullCycleCoveragePct;$m.pcFirstFinalists=$pc.summary.finalistCount};Invoke-AgentPost '/api/agent/scan' $m|Out-Null};if(-not $script:LastCleanupAt -or ([DateTime]::UtcNow-$script:LastCleanupAt).TotalMinutes-ge 30){Invoke-LocalCleanup};$script:LastError=$null}catch{$script:LastError=$_.Exception.Message;Write-AgentLog "FEHLER: $script:LastError"};$sec=60-(Get-Date).Second;if($sec-lt 5){$sec+=60};Start-Sleep -Seconds $sec}
