#!/usr/bin/env python3
from __future__ import annotations
import json
from pathlib import Path
import yfinance as yf

OUT=Path(__file__).resolve().parents[1]/"src"/"generated-zero-etfs.js"
TARGET_COUNT=2200
ZERO_ADVERTISED_ETFS=2000
EXCHANGES=["GER","FRA","MUN","STU"]
OFFSETS=range(0,3000,250)
BLOCKED=("LEVERAGED","INVERSE","BEAR ","2X ","3X ","-2X","-3X","SHORT ","ULTRASHORT")
KNOWN_UCITS_FAMILIES=("ISHARES","VANGUARD","XTRACKERS","AMUNDI","SPDR","VANECK","WISDOMTREE","INVESCO","HSBC","UBS","FRANKLIN","JPM","JPMORGAN","LEGAL & GENERAL","L&G","DEKA","LYXOR","BNP PARIBAS","FIDELITY")

def n(v,default=0.0):
    try:return float(v)
    except Exception:return default

def txt(q,*keys):
    for k in keys:
        v=q.get(k)
        if v is not None and str(v).strip():return str(v).strip()
    return ""

def collect(exchange):
    q=yf.ETFQuery("and",[
        yf.ETFQuery("eq",["exchange",exchange]),
        yf.ETFQuery("gt",["intradayprice",0]),
    ])
    out=[]
    for off in OFFSETS:
        try:
            r=yf.screen(q,offset=off,size=250,sortField="fundnetassets",sortAsc=False)
            batch=r.get("quotes",[]) or []
            out.extend(batch)
            if len(batch)<250:break
        except Exception:
            break
    return out

def is_normal_ucits(name,category):
    u=f"{name} {category}".upper()
    if any(x in u for x in BLOCKED):return False
    return "UCITS" in u or any(f in u for f in KNOWN_UCITS_FAMILIES)

def main():
    rows=[]
    for ex in EXCHANGES:rows.extend(collect(ex))
    by_symbol={}
    for q in rows:
        sym=txt(q,"symbol").upper()
        if not sym:continue
        name=txt(q,"longName","shortName","displayName","name") or sym
        category=txt(q,"categoryName","categoryname","category") or "ETF"
        if not is_normal_ucits(name,category):continue
        vol=n(q.get("averageDailyVolume3Month"),n(q.get("avgdailyvol3m"),n(q.get("eodvolume"),0)))
        assets=n(q.get("fundNetAssets"),n(q.get("fundnetassets"),0))
        expense=n(q.get("annualReportNetExpenseRatio"),n(q.get("annualreportnetexpenseratio"),0))
        price=n(q.get("regularMarketPrice"),n(q.get("intradayprice"),0))
        if price<=0:continue
        item={"symbol":sym,"name":name,"theme":category,"volume":vol,"assets":assets,"expense":expense,"price":price}
        old=by_symbol.get(sym)
        if old is None or (assets,vol,price)>(old["assets"],old["volume"],old["price"]):by_symbol[sym]=item
    ranked=sorted(by_symbol.values(),key=lambda x:(x["assets"],x["volume"],x["price"]),reverse=True)[:TARGET_COUNT]
    lines=["// AUTO-GENERATED by scripts/refresh_etfs.py. Do not edit manually.","// ZERO-scale pool of normal German-tradable ETF candidates.","// Not an asserted exact ZERO catalog: concrete broker availability must be verified before a live order.",f"// Current ZERO reference size: >={ZERO_ADVERTISED_ETFS} ETFs; target candidate pool: {TARGET_COUNT}.","export const GENERATED_ZERO_ETFS = ["]
    for x in ranked:
        obj={"symbol":x["symbol"],"name":x["name"],"theme":x["theme"],"type":"ETF","leverage":1,"broker":"finanzen.net ZERO","venue":"gettex","ucits":True,"brokerCatalogCandidate":True,"brokerVerified":False,"priority":False,"generated":True}
        lines.append("  "+json.dumps(obj,ensure_ascii=False,separators=(",",":"))+",")
    lines.append("];\n")
    OUT.write_text("\n".join(lines),encoding="utf-8")
    print(f"Wrote {len(ranked)} normal ETF candidates toward ZERO-scale pool to {OUT}")

if __name__=="__main__":main()
