#!/usr/bin/env python3
from __future__ import annotations
import json
from pathlib import Path
import yfinance as yf

OUT=Path(__file__).resolve().parents[1]/"src"/"generated-zero-etfs.js"
TARGET_COUNT=60
EXCHANGES=["GER","FRA"]
BLOCKED=("LEVERAGED","INVERSE","BEAR ","2X ","3X ","-2X","-3X","SHORT ","ULTRASHORT")
KNOWN_UCITS_FAMILIES=("ISHARES","VANGUARD","XTRACKERS","AMUNDI","SPDR","VANECK","WISDOMTREE","INVESCO","HSBC","UBS","FRANKLIN","JPM","JPMORGAN","LEGAL & GENERAL","L&G")

def n(v,default=0.0):
    try:return float(v)
    except Exception:return default

def txt(q,*keys):
    for k in keys:
        v=q.get(k)
        if v is not None and str(v).strip():return str(v).strip()
    return ""

def collect(exchange):
    q=yf.ETFQuery("and",[
        yf.ETFQuery("eq",["exchange",exchange]),
        yf.ETFQuery("gt",["intradayprice",1]),
    ])
    out=[]
    for off in (0,250,500):
        try:
            r=yf.screen(q,offset=off,size=250,sortField="fundnetassets",sortAsc=False)
            batch=r.get("quotes",[]) or []
            out.extend(batch)
            if len(batch)<250:break
        except Exception:
            break
    return out

def is_normal_ucits(name,category):
    u=f"{name} {category}".upper()
    if any(x in u for x in BLOCKED):return False
    # German-listed products from established ETF families are treated only as
    # normal UCITS candidates. Exact ZERO availability is still rechecked before live use.
    return "UCITS" in u or any(f in u for f in KNOWN_UCITS_FAMILIES)

def main():
    rows=[]
    for ex in EXCHANGES:rows.extend(collect(ex))
    by_symbol={}
    for q in rows:
        sym=txt(q,"symbol").upper()
        if not sym:continue
        name=txt(q,"longName","shortName","displayName","name") or sym
        category=txt(q,"categoryName","categoryname","category") or "ETF"
        if not is_normal_ucits(name,category):continue
        vol=n(q.get("averageDailyVolume3Month"),n(q.get("avgdailyvol3m"),n(q.get("eodvolume"),0)))
        assets=n(q.get("fundNetAssets"),n(q.get("fundnetassets"),0))
        expense=n(q.get("annualReportNetExpenseRatio"),n(q.get("annualreportnetexpenseratio"),0))
        if vol<=0 and assets<=0:continue
        item={"symbol":sym,"name":name,"theme":category,"volume":vol,"assets":assets,"expense":expense}
        old=by_symbol.get(sym)
        if old is None or (assets,vol)>(old["assets"],old["volume"]):by_symbol[sym]=item
    ranked=sorted(by_symbol.values(),key=lambda x:(x["assets"],x["volume"]),reverse=True)[:TARGET_COUNT]
    lines=["// AUTO-GENERATED by scripts/refresh_etfs.py. Do not edit manually.","// Broad German-listed normal ETF candidates for the ZERO/gettex paper-trading target.","// This is NOT an exact broker catalog; live broker availability must be rechecked.","export const GENERATED_ZERO_ETFS = ["]
    for x in ranked:
        obj={"symbol":x["symbol"],"name":x["name"],"theme":x["theme"],"type":"ETF","leverage":1,"broker":"finanzen.net ZERO","venue":"gettex","ucits":True,"brokerEligible":True,"priority":False,"generated":True}
        lines.append("  "+json.dumps(obj,ensure_ascii=False,separators=(",",":"))+",")
    lines.append("];\n")
    OUT.write_text("\n".join(lines),encoding="utf-8")
    print(f"Wrote {len(ranked)} generated normal ETF candidates to {OUT}")

if __name__=="__main__":main()
