import {CORE_ETFS,LEVERAGED_ETFS,SPARK_BATCH,DEEP_LIMIT,NEWS_LIMIT,NEWS_RADAR_BATCH,POS_WORDS,NEG_WORDS,clamp,num,chunks} from './constants.js';
import {PRIORITY_EQUITIES} from './priority-equities.js';
import {selectBalancedDeepCandidates} from './deep-candidate-selection.js';
import {quoteCurrencyInfo,normalizeQuoteCurrency,normalizeQuotePrice} from './quote-currency-units.js';

const headers={'accept':'application/json','user-agent':'Mozilla/5.0'};
const feedHeaders={'accept':'application/rss+xml,application/xml,text/xml,application/json,text/html;q=0.8,*/*;q=0.5','user-agent':'Mozilla/5.0 (compatible; KI-Markt-Planspiel/4.2; +https://github.com/plasma19911/ki-markt-planspiel)'};
const POS_PHRASES=['contract award','awarded contract','wins contract','selected for','raises guidance','raised guidance','beats estimates','beat estimates','record orders','record backlog','backlog growth','approval granted','strategic partnership','new customer','buyback','dividend increase','upgraded to buy','price target raised','funding secured','production increase','guidance raised','strong demand','auftrag','großauftrag','rekordauftrag','prognose angehoben','gewinn steigt','umsatz steigt','übertrifft erwartungen','uebertrifft erwartungen'];
const NEG_PHRASES=['contract cancelled','contract canceled','loses contract','cuts guidance','cut guidance','misses estimates','missed estimates','investigation','regulatory probe','data breach','cyberattack','production delay','delivery delay','recall','downgraded to sell','price target cut','bankruptcy','default','fraud allegation','export ban','guidance lowered','prognose gesenkt','gewinnwarnung','umsatzwarnung','verfehlt erwartungen','ermittlungen'];
const NEWS_MAX_TRADING_AGE_HOURS=36;
const MOMENTUM_BREAKOUT_RESERVE=Math.max(3,Math.min(8,Math.ceil(DEEP_LIMIT*.35)));

export const BENCHMARKS=[
 {symbol:'VWCE.DE',name:'Vanguard FTSE All-World',type:'BENCHMARK',leverage:1,benchmark:true},
 {symbol:'QQQ',name:'Nasdaq-100 / QQQ',type:'BENCHMARK',leverage:1,benchmark:true},
 {symbol:'SPY',name:'S&P 500 / SPY',type:'BENCHMARK',leverage:1,benchmark:true}
];

const SESSION_RULES=[
 [/\.DE$/,'Europe/Berlin',9*60,17*60+30,'Deutschland','XETR','EUR'],[/\.(F|SG|MU|HM)$/,'Europe/Berlin',9*60,17*60+30,'Deutschland','XETR','EUR'],
 [/\.(PA|BR|MI|MC)$/,'Europe/Paris',9*60,17*60+30,'Europa','XPAR','EUR'],[/\.AS$/,'Europe/Amsterdam',9*60,17*60+30,'Amsterdam','XAMS','EUR'],
 [/\.VI$/,'Europe/Vienna',9*60,17*60+30,'Wien','XWBO','EUR'],[/\.HE$/,'Europe/Helsinki',10*60,18*60+30,'Helsinki','XHEL','EUR'],
 [/\.CO$/,'Europe/Copenhagen',9*60,17*60,'Kopenhagen','XCSE','DKK'],[/\.LS$/,'Europe/Lisbon',8*60,16*60+30,'Lissabon','XLIS','EUR'],
 [/\.SW$/,'Europe/Zurich',9*60,17*60+30,'Schweiz','XSWX','CHF'],[/\.L$/,'Europe/London',8*60,16*60+30,'London','XLON','GBP'],
 [/\.ST$/,'Europe/Stockholm',9*60,17*60+30,'Stockholm','XSTO','SEK'],[/\.OL$/,'Europe/Oslo',9*60,16*60+30,'Oslo','XOSL','NOK'],
 [/\.SR$/,'Asia/Riyadh',10*60,15*60,'Saudi-Arabien','XSAU','SAR'],[/\.IS$/,'Europe/Istanbul',10*60,18*60,'Istanbul','XIST','TRY'],[/\.WA$/,'Europe/Warsaw',9*60,17*60,'Warschau','XWAR','PLN'],
 [/\.PR$/,'Europe/Prague',9*60,16*60+20,'Prag','XPRA','CZK'],[/\.T$/,'Asia/Tokyo',9*60,15*60+30,'Tokio','XTKS','JPY'],
 [/\.(KS|KQ)$/,'Asia/Seoul',9*60,15*60+30,'Seoul','XKRX','KRW'],[/\.(TW|TWO)$/,'Asia/Taipei',9*60,13*60+30,'Taiwan','XTAI','TWD'],
 [/\.HK$/,'Asia/Hong_Kong',9*60+30,16*60,'Hongkong','XHKG','HKD'],[/\.(SS|SZ)$/,'Asia/Shanghai',9*60+30,15*60,'China','XSHG','CNY'],
 [/\.(NS|BO)$/,'Asia/Kolkata',9*60+15,15*60+30,'Indien','XNSE','INR'],[/\.SI$/,'Asia/Singapore',9*60,17*60,'Singapur','XSES','SGD'],
 [/\.BK$/,'Asia/Bangkok',10*60,16*60+30,'Thailand','XBKK','THB'],[/\.JK$/,'Asia/Jakarta',9*60,16*60,'Indonesien','XIDX','IDR'],
 [/\.KL$/,'Asia/Kuala_Lumpur',9*60,17*60,'Malaysia','XKLS','MYR'],[/\.TA$/,'Asia/Jerusalem',10*60,17*60+25,'Tel Aviv','XTAE','ILS'],
 [/\.AX$/,'Australia/Sydney',10*60,16*60,'Australien','XASX','AUD'],[/\.NZ$/,'Pacific/Auckland',10*60,16*60+45,'Neuseeland','XNZE','NZD'],
 [/\.(TO|V|NE)$/,'America/Toronto',9*60+30,16*60,'Kanada','XTSE','CAD'],[/\.MX$/,'America/Mexico_City',8*60+30,15*60,'Mexiko','XMEX','MXN'],
 [/\.SA$/,'America/Sao_Paulo',10*60,17*60,'Brasilien','BVMF','BRL'],[/\.JO$/,'Africa/Johannesburg',9*60,17*60,'Suedafrika','XJSE','ZAR']
];

const EXCHANGE_RULES=[
 [new Set(['NMS','NYQ','NGM','NCM','ASE','PCX']),[null,'America/New_York',9*60+30,16*60,'USA','XNYS','USD']],
 [new Set(['GER','FRA','STU','MUN','DUS','HAM']),[null,'Europe/Berlin',9*60,17*60+30,'Deutschland','XETR','EUR']],
 [new Set(['PAR','BRU']),[null,'Europe/Paris',9*60,17*60+30,'Europa','XPAR','EUR']],
 [new Set(['MIL','MCE']),[null,'Europe/Paris',9*60,17*60+30,'Europa','XMIL','EUR']],
 [new Set(['AMS']),[null,'Europe/Amsterdam',9*60,17*60+30,'Amsterdam','XAMS','EUR']],
 [new Set(['VIE']),[null,'Europe/Vienna',9*60,17*60+30,'Wien','XWBO','EUR']],
 [new Set(['HEL']),[null,'Europe/Helsinki',10*60,18*60+30,'Helsinki','XHEL','EUR']],
 [new Set(['CPH']),[null,'Europe/Copenhagen',9*60,17*60,'Kopenhagen','XCSE','DKK']],
 [new Set(['LSE','IOB']),[null,'Europe/London',8*60,16*60+30,'London','XLON','GBP']],
 [new Set(['EBS']),[null,'Europe/Zurich',9*60,17*60+30,'Schweiz','XSWX','CHF']],
 [new Set(['STO']),[null,'Europe/Stockholm',9*60,17*60+30,'Stockholm','XSTO','SEK']],
 [new Set(['OSL']),[null,'Europe/Oslo',9*60,16*60+30,'Oslo','XOSL','NOK']],
 [new Set(['JPX','TYO']),[null,'Asia/Tokyo',9*60,15*60+30,'Tokio','XTKS','JPY']],
 [new Set(['KSC','KOE']),[null,'Asia/Seoul',9*60,15*60+30,'Seoul','XKRX','KRW']],
 [new Set(['TAI','TWO']),[null,'Asia/Taipei',9*60,13*60+30,'Taiwan','XTAI','TWD']],
 [new Set(['HKG']),[null,'Asia/Hong_Kong',9*60+30,16*60,'Hongkong','XHKG','HKD']],
 [new Set(['SHH','SHZ']),[null,'Asia/Shanghai',9*60+30,15*60,'China','XSHG','CNY']],
 [new Set(['NSI','BSE']),[null,'Asia/Kolkata',9*60+15,15*60+30,'Indien','XNSE','INR']],
 [new Set(['ASX']),[null,'Australia/Sydney',10*60,16*60,'Australien','XASX','AUD']],
 [new Set(['TOR','VAN','NEO']),[null,'America/Toronto',9*60+30,16*60,'Kanada','XTSE','CAD']],
 [new Set(['MEX']),[null,'America/Mexico_City',8*60+30,15*60,'Mexiko','XMEX','MXN']],
 [new Set(['SAO']),[null,'America/Sao_Paulo',10*60,17*60,'Brasilien','BVMF','BRL']],
 [new Set(['JNB']),[null,'Africa/Johannesburg',9*60,17*60,'Suedafrika','XJSE','ZAR']],
 [new Set(['SES']),[null,'Asia/Singapore',9*60,17*60,'Singapur','XSES','SGD']],
 [new Set(['SAU']),[null,'Asia/Riyadh',10*60,15*60,'Saudi-Arabien','XSAU','SAR']]
];
const CURRENCY_RULES={SAR:[null,'Asia/Riyadh',10*60,15*60,'Saudi-Arabien','XSAU','SAR'],EUR:[null,'Europe/Paris',9*60,17*60+30,'Europa','XPAR','EUR'],GBP:[null,'Europe/London',8*60,16*60+30,'London','XLON','GBP'],CHF:[null,'Europe/Zurich',9*60,17*60+30,'Schweiz','XSWX','CHF'],SEK:[null,'Europe/Stockholm',9*60,17*60+30,'Stockholm','XSTO','SEK'],NOK:[null,'Europe/Oslo',9*60,16*60+30,'Oslo','XOSL','NOK'],DKK:[null,'Europe/Copenhagen',9*60,17*60,'Kopenhagen','XCSE','DKK'],TRY:[null,'Europe/Istanbul',10*60,18*60,'Istanbul','XIST','TRY'],JPY:[null,'Asia/Tokyo',9*60,15*60+30,'Tokio','XTKS','JPY'],KRW:[null,'Asia/Seoul',9*60,15*60+30,'Seoul','XKRX','KRW'],TWD:[null,'Asia/Taipei',9*60,13*60+30,'Taiwan','XTAI','TWD'],HKD:[null,'Asia/Hong_Kong',9*60+30,16*60,'Hongkong','XHKG','HKD'],CNY:[null,'Asia/Shanghai',9*60+30,15*60,'China','XSHG','CNY'],INR:[null,'Asia/Kolkata',9*60+15,15*60+30,'Indien','XNSE','INR'],AUD:[null,'Australia/Sydney',10*60,16*60,'Australien','XASX','AUD'],CAD:[null,'America/Toronto',9*60+30,16*60,'Kanada','XTSE','CAD'],MXN:[null,'America/Mexico_City',8*60+30,15*60,'Mexiko','XMEX','MXN'],BRL:[null,'America/Sao_Paulo',10*60,17*60,'Brasilien','BVMF','BRL'],ZAR:[null,'Africa/Johannesburg',9*60,17*60,'Suedafrika','XJSE','ZAR'],SGD:[null,'Asia/Singapore',9*60,17*60,'Singapur','XSES','SGD']};

const health=()=>({});
function markHealth(h,source,ok,error='',started=0){const x=h[source]||{ok:0,fail:0,lastError:'',latencyMs:null};if(ok){x.ok++;x.lastError=''}else{x.fail++;x.lastError=String(error||'Fehler').slice(0,180)}if(started)x.latencyMs=Date.now()-started;h[source]=x}
function sourceHealthSummary(h){const out={};for(const [k,v] of Object.entries(h))out[k]={status:v.fail>0&&v.ok===0?'DOWN':v.fail>0?'DEGRADED':'OK',okCount:v.ok,failCount:v.fail,lastError:v.lastError,latencyMs:v.latencyMs};return out}

function ema(a,p){if(a.length<p)return null;const k=2/(p+1);let e=a.slice(0,p).reduce((x,y)=>x+y,0)/p;for(const v of a.slice(p))e=v*k+e*(1-k);return e}
function rsi(a,p=14){if(a.length<p+1)return null;let g=0,l=0,s=a.slice(-(p+1));for(let i=1;i<s.length;i++){const d=s[i]-s[i-1];d>0?g+=d:l-=d}if(!l)return 100;const rs=(g/p)/(l/p);return 100-100/(1+rs)}
function decodeText(x){return String(x||'').replace(/<!\[CDATA\[|\]\]>/g,'').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim()}
function normalizeHeadline(x){return decodeText(x).toLowerCase().replace(/[^a-z0-9äöüß ]+/gi,' ').replace(/\s+/g,' ').trim().slice(0,260)}
function tokens(x){return new Set(normalizeHeadline(x).split(' ').filter(w=>w.length>=4&&!['with','from','that','this','after','over','into','says','amid','mehr','nach','ueber','über','gegen','durch','einer','einem','aktie','aktien','company','corporation'].includes(w)))}
function similarity(a,b){const A=tokens(a),B=tokens(b);if(!A.size||!B.size)return 0;let i=0;for(const x of A)if(B.has(x))i++;return i/(A.size+B.size-i)}
function headlineSentiment(h){const text=String(h||'').toLowerCase();let s=0;for(const p of POS_PHRASES)if(text.includes(p))s+=.85;for(const p of NEG_PHRASES)if(text.includes(p))s-=.9;for(const w of text.replace(/[^a-z0-9]+/g,' ').split(/\s+/)){if(POS_WORDS.includes(w))s+=.18;if(NEG_WORDS.includes(w))s-=.18}return clamp(s,-2,2)}
function newsItems(xml,limit=40){const out=[];for(const m of String(xml).matchAll(/<item>([\s\S]*?)<\/item>/gi)){const b=m[1],title=decodeText(b.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1]),pub=decodeText(b.match(/<(?:pubDate|dc:date|date)[^>]*>([\s\S]*?)<\/(?:pubDate|dc:date|date)>/i)?.[1]);if(title)out.push({title,publishedAt:pub&&Number.isFinite(Date.parse(pub))?new Date(pub).toISOString():null})}for(const m of String(xml).matchAll(/<entry>([\s\S]*?)<\/entry>/gi)){const b=m[1],title=decodeText(b.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1]),pub=decodeText(b.match(/<(?:updated|published)[^>]*>([\s\S]*?)<\/(?:updated|published)>/i)?.[1]);if(title)out.push({title,publishedAt:pub&&Number.isFinite(Date.parse(pub))?new Date(pub).toISOString():null})}return out.slice(0,limit)}
function jsonNewsItems(text,limit=40){try{const root=JSON.parse(text),out=[],seen=new Set();const walk=x=>{if(!x||out.length>=limit*3)return;if(Array.isArray(x)){for(const y of x)walk(y);return}if(typeof x!=='object')return;const title=decodeText(x.title||x.headline||x.name||x.subject||'');const rawDate=x.publishedAt||x.published||x.date||x.datetime||x.createdAt||x.created||x.timestamp||x.time;if(title&&title.length>12&&!seen.has(title)){seen.add(title);let publishedAt=null;if(typeof rawDate==='number')publishedAt=new Date(rawDate>1e12?rawDate:rawDate*1000).toISOString();else if(rawDate&&Number.isFinite(Date.parse(rawDate)))publishedAt=new Date(rawDate).toISOString();out.push({title,publishedAt})}for(const v of Object.values(x))if(v&&typeof v==='object')walk(v)};walk(root);return out.slice(0,limit)}catch{return[]}}
function parseFeed(text,limit=40){const t=String(text||'').trim();if(!t)return[];return (t.startsWith('{')||t.startsWith('[')?jsonNewsItems(t,limit):newsItems(t,limit))}
async function mapLimit(items,limit,fn){const out=new Array(items.length);let i=0;await Promise.all(Array.from({length:Math.min(limit,items.length)},async()=>{while(true){const x=i++;if(x>=items.length)return;try{out[x]=await fn(items[x])}catch{out[x]=null}}}));return out}

function sessionRule(info){for(const r of SESSION_RULES)if(r[0].test(String(info?.symbol||'')))return r;const ex=String(info?.exchange||'').toUpperCase();for(const [set,r] of EXCHANGE_RULES)if(set.has(ex))return r;let cur=String(info?.currency||'').trim();if(cur==='GBp'||cur.toUpperCase()==='GBX')cur='GBP';cur=cur.toUpperCase();return CURRENCY_RULES[cur]||[null,'America/New_York',9*60+30,16*60,'USA','XNYS','USD']}
function localParts(date,tz){const p=new Intl.DateTimeFormat('en-CA',{timeZone:tz,year:'numeric',month:'2-digit',day:'2-digit',weekday:'short',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(date),o={};for(const x of p)o[x.type]=x.value;return o}
function ymdFromParts(p){return `${p.year}-${p.month}-${p.day}`}
function ordFromParts(p){return Math.floor(Date.UTC(Number(p.year),Number(p.month)-1,Number(p.day))/86400000)}
function ymdFromOrd(ord){const d=new Date(ord*86400000);return `${d.getUTCFullYear()}-${String(d.getUTCMonth()+1).padStart(2,'0')}-${String(d.getUTCDate()).padStart(2,'0')}`}
function minsOfParts(p){return num(p.hour)*60+num(p.minute)}
function rawCurrency(info){return info?.quoteCurrencyRaw||info?.quote_currency_raw||info?.currency||sessionRule(info)[6]||'USD'}
function inferCurrency(info){return normalizeQuoteCurrency(rawCurrency(info))}
function sessionWindow(info,ymd,weekdayIndex,calendar){const r=sessionRule(info),code=r[5],fallback=[r[2],r[3]];const e=calendar?.exchanges?.[code]?.[ymd];if(e?.closed)return null;if(e?.open&&e?.close){const p=x=>{const [h,m]=String(x).split(':').map(Number);return h*60+m};return[p(e.open),p(e.close)]}if(code==='XSAU'){if(weekdayIndex===5||weekdayIndex===6)return null}else if(weekdayIndex===0||weekdayIndex===6)return null;return fallback}
export function marketOpen(info,date=new Date(),calendar=null){const r=sessionRule(info),p=localParts(date,r[1]),ord=ordFromParts(p),w=new Date(ord*86400000).getUTCDay(),window=sessionWindow(info,ymdFromParts(p),w,calendar);if(!window)return{open:false,label:r[4],exchange:r[5],currency:inferCurrency(info)};const mins=minsOfParts(p);return{open:mins>=window[0]&&mins<window[1],label:r[4],exchange:r[5],currency:inferCurrency(info),openMinute:window[0],closeMinute:window[1]}}

export function newsTradingAgeHours(info,ts,now=new Date(),calendar=null){const t=Date.parse(ts||'');if(!Number.isFinite(t)||t>now.getTime())return 0;const r=sessionRule(info),a=localParts(new Date(t),r[1]),b=localParts(now,r[1]),oa=ordFromParts(a),ob=ordFromParts(b),am=minsOfParts(a),bm=minsOfParts(b);let minutes=0;for(let ord=oa;ord<=ob&&ord-oa<45;ord++){const weekday=new Date(ord*86400000).getUTCDay(),window=sessionWindow(info,ymdFromOrd(ord),weekday,calendar);if(!window)continue;let lo=window[0],hi=window[1];if(ord===oa)lo=Math.max(lo,am);if(ord===ob)hi=Math.min(hi,bm);if(hi>lo)minutes+=hi-lo}return minutes/60}
export function newsRecencyWeight(info,ts,calendar=null){const h=newsTradingAgeHours(info,ts,new Date(),calendar);if(h<=.25)return 1.75;if(h<=1)return 1.55;if(h<=3)return 1.30;if(h<=6)return 1;if(h<=12)return .62;if(h<=18)return .35;if(h<=24)return .16;if(h<=36)return .05;return 0}

async function loadCalendar(env){try{const r=await env.ASSETS.fetch(new Request('https://assets.local/market-calendar.json'));if(r.ok)return await r.json()}catch{}return{exchanges:{}}}
function liveCompanyKey(x){if(x?.type==='ETF'||x?.type==='BENCHMARK')return `${x.type}:${x.symbol}`;if(x?.companyKey)return `EQ:${String(x.companyKey).toUpperCase()}`;const junk=new Set(['INC','INCORPORATED','CORP','CORPORATION','CO','COMPANY','LTD','LIMITED','PLC','AG','SE','NV','SA','SPA','HOLDING','HOLDINGS','GROUP','ORD','ORDINARY','SHARE','SHARES','SHS','REGISTERED','REG','ADR','GDR','CDR','DRN','BDR','ADS','CLASS','CL','SERIES','THE','AND','R','ED','HEDGED']);const toks=String(x?.name||x?.symbol||'').toUpperCase().replace(/[^A-Z0-9]+/g,' ').split(/\s+/).filter(Boolean).filter(t=>t.length>1&&!junk.has(t)).map(t=>t.length>9?t.slice(0,9):t),u=[];for(const t of toks)if(u.at(-1)!==t)u.push(t);return `EQ:${u.slice(0,7).join(' ')||String(x?.symbol||'').split('.')[0]}`}
export async function loadUniverse(env,cfg){let data={equities:[],generated_at:null};try{const r=await env.ASSETS.fetch(new Request('https://assets.local/universe.json'));if(r.ok)data=await r.json()}catch{}const all=(data.equities||[]).filter(x=>x?.symbol).map(x=>({symbol:String(x.symbol).toUpperCase(),name:x.name||x.symbol,type:'EQUITY',leverage:1,marketCap:num(x.marketCap),marketCapUSD:num(x.marketCapUSD),companyKey:x.companyKey||null,region:x.region||null,exchange:x.exchange||null,currency:x.currency||null}));all.push(...PRIORITY_EQUITIES);if(cfg.include_etfs)all.push(...CORE_ETFS);if(cfg.include_leverage)all.push(...LEVERAGED_ETFS);const seenSymbol=new Set(),seenCompany=new Set(),out=[];for(const x of all){if(seenSymbol.has(x.symbol))continue;const key=liveCompanyKey(x);if(x.type==='EQUITY'&&seenCompany.has(key))continue;seenSymbol.add(x.symbol);if(x.type==='EQUITY')seenCompany.add(key);out.push({...x,quoteCurrencyRaw:rawCurrency(x),quotePriceScale:quoteCurrencyInfo(rawCurrency(x)).priceScale,currency:inferCurrency(x),companyKey:x.companyKey||key.replace(/^EQ:/,'')})}return{items:out,generatedAt:data.generated_at}}

async function sparkRaw(symbols,h,source='Yahoo Spark'){if(!symbols.length)return[];const started=Date.now();try{const u=new URL('https://query1.finance.yahoo.com/v7/finance/spark');u.searchParams.set('symbols',symbols.join(','));u.searchParams.set('range','1d');u.searchParams.set('interval','5m');u.searchParams.set('indicators','close');u.searchParams.set('includePrePost','false');const r=await fetch(u,{headers});if(!r.ok)throw new Error(`HTTP ${r.status}`);const j=await r.json();markHealth(h,source,true,'',started);return j?.spark?.result||[]}catch(e){markHealth(h,source,false,e,started);return[]}}
async function sparkBatch(items,h){const lookup=new Map(items.map(x=>[x.symbol,x])),raw=await sparkRaw(items.map(x=>x.symbol),h),out=[];for(const item of raw){const res=item?.response?.[0];if(!res)continue;const m=res.meta||{},sym=String(item.symbol||m.symbol||'').toUpperCase(),info=lookup.get(sym);if(!info)continue;const c=(res?.indicators?.quote?.[0]?.close||[]).filter(v=>Number.isFinite(Number(v))).map(Number);if(c.length<1)continue;const price=num(m.regularMarketPrice,c.at(-1)),prev=num(m.previousClose,c[0]),day=prev?(price/prev-1)*100:0,back=c[Math.max(0,c.length-4)],mom=back?(price/back-1)*100:0,prevA=c[Math.max(0,c.length-7)],prevB=c[Math.max(0,c.length-4)],prevMom=prevA&&prevB?(prevB/prevA-1)*100:0,accel=mom-prevMom,high25=Math.max(...c.slice(-5)),nearHigh=high25>0&&price>=high25*.998,breakoutPre=mom>.35&&accel>.08&&day>0&&nearHigh,breakoutPreScore=Math.max(0,mom*1.8+Math.max(accel,0)*1.4+Math.max(day,0)*.25+(nearHigh?.35:0)),age=m.regularMarketTime?Date.now()/1000-num(m.regularMarketTime):999999;const liveRawCurrency=m.currency||rawCurrency(info),liveUnit=quoteCurrencyInfo(liveRawCurrency);out.push({...info,currency:liveUnit.majorCurrency||inferCurrency(info),quoteCurrencyRaw:liveRawCurrency,quotePriceScale:liveUnit.priceScale,quoteUnitNormalized:true,price:normalizeQuotePrice(price,liveRawCurrency),dayChange:day,coarseMomentum:mom,momentumAcceleration:accel,breakoutPre,breakoutPreScore,preScore:day*.65+mom*1.35,fresh:age<35*60,marketTimestamp:m.regularMarketTime||null})}return out}

async function fxRates(currencies,base,h){const out={[base]:1},needed=[...new Set(currencies.filter(c=>c&&c!==base))];if(!needed.length)return out;const pairs=[];for(const c of needed){pairs.push(`${c}${base}=X`,`${base}${c}=X`)}const raw=await sparkRaw(pairs,h,'Yahoo FX');const px={};for(const item of raw){const res=item?.response?.[0],sym=String(item.symbol||res?.meta?.symbol||'').toUpperCase(),v=num(res?.meta?.regularMarketPrice,res?.indicators?.quote?.[0]?.close?.filter(Number.isFinite)?.at(-1));if(sym&&v>0)px[sym]=v}for(const c of needed){const direct=px[`${c}${base}=X`],inverse=px[`${base}${c}=X`];out[c]=direct>0?direct:inverse>0?1/inverse:1}return out}

async function deepChart(info,h){const started=Date.now();try{const u=new URL(`https://query1.finance.yahoo.com/v8/finance/chart/${encodeURIComponent(info.symbol)}`);u.searchParams.set('range','1d');u.searchParams.set('interval','1m');u.searchParams.set('includePrePost','false');const r=await fetch(u,{headers});if(!r.ok)throw new Error(`HTTP ${r.status}`);const j=await r.json(),res=j?.chart?.result?.[0];if(!res)throw new Error('Keine Chartdaten');const q=res?.indicators?.quote?.[0]||{},cl=(q.close||[]).filter(v=>Number.isFinite(Number(v))).map(Number),vol=(q.volume||[]).map(v=>num(v));if(cl.length<22)throw new Error('Zu wenig Minuten');const price=cl.at(-1),e9=ema(cl,9),e21=ema(cl,21),rr=rsi(cl),m5=(price/cl.at(-6)-1)*100,m20=(price/cl.at(-21)-1)*100,prev5=cl.length>=11?(cl.at(-6)/cl.at(-11)-1)*100:0,accel5=m5-prev5,recent3=cl.length>=4?(price/cl.at(-4)-1)*100:m5,high20=Math.max(...cl.slice(-21,-1)),drawFromHigh=high20?(price/high20-1)*100:0,pclose=num(res.meta?.previousClose,cl[0]),day=pclose?(price/pclose-1)*100:0,vbase=vol.slice(-21,-1).filter(x=>x>0),vavg=vbase.length?vbase.reduce((a,b)=>a+b,0)/vbase.length:0,vr=vavg?num(vol.at(-1))/vavg:1,last=(res.timestamp||[]).at(-1)||res.meta?.regularMarketTime||0,fresh=Date.now()/1000-last<35*60;let score=0,pro=[],contra=[];if(e9&&e21&&e9>e21){score+=1.7;pro.push('EMA9 über EMA21')}else{score-=1;contra.push('EMA-Trend schwach')}if(e21&&price>e21){score+=.8;pro.push('Kurs über EMA21')}else{score-=.6;contra.push('Kurs unter EMA21')}if(rr!==null){if(rr>=48&&rr<=68){score+=1;pro.push(`RSI ${rr.toFixed(0)} konstruktiv`)}else if(rr>=78){score-=1.5;contra.push(`RSI ${rr.toFixed(0)} überhitzt`)}else if(rr<=32){score-=.8;contra.push(`RSI ${rr.toFixed(0)} sehr schwach`)}}if(m5>.18){score+=.8;pro.push(`5m +${m5.toFixed(2)}%`)}else if(m5<-.25){score-=.9;contra.push(`5m ${m5.toFixed(2)}%`)}if(m20>.5){score+=1.2;pro.push(`20m +${m20.toFixed(2)}%`)}else if(m20<-.5){score-=1.2;contra.push(`20m ${m20.toFixed(2)}%`)}if(vr>1.5){score+=.7;pro.push(`Volumen x${vr.toFixed(1)}`)}if(day>1)score+=.4;if(day<-1)score-=.5;
 const trendUp=Boolean(e9&&e21&&e9>e21&&price>e21),breakoutScore=clamp(Math.max(0,m5)*1.6+Math.max(0,m20)*.8+Math.max(0,accel5)*1.5+Math.max(0,vr-1)*.55+Math.max(0,drawFromHigh+.25),0,10),confirmedBreakout=trendUp&&m5>.22&&m20>.55&&accel5>.03&&vr>=1.2&&drawFromHigh>=-.25&&(rr==null||rr<78);let momentumState='NORMAL',momentumSellSignal='NONE',exhaustion=0;if(confirmedBreakout){momentumState='BREAKOUT';score+=1.6;pro.push(`MOMENTUM-BREAKOUT ${breakoutScore.toFixed(1)} · Beschleunigung ${accel5>=0?'+':''}${accel5.toFixed(2)}%`)}else if(trendUp&&m5>.12&&m20>.35&&accel5>0){momentumState='BUILDING';score+=.55;pro.push(`Momentum baut sich auf · Beschleunigung +${accel5.toFixed(2)}%`)}const hadStrongRun=m20>.8||day>1.5||num(info.breakoutPreScore)>1.7;if(hadStrongRun){if(rr!=null&&rr>=74)exhaustion+=.5;if(accel5<-.2)exhaustion+=1;if(m5<0)exhaustion+=1;if(e9&&price<e9)exhaustion+=1;if(drawFromHigh<-.6)exhaustion+=1;if(vr>1.5&&recent3<0)exhaustion+=.5}if(exhaustion>=3){momentumState='REVERSAL';momentumSellSignal='STRONG';score-=3;contra.push(`MOMENTUM-REVERSAL stark (${exhaustion.toFixed(1)}): Lauf kippt · Verkauf/Absicherung prüfen`)}else if(exhaustion>=1.75){momentumState='EXHAUSTION';momentumSellSignal='WATCH';score-=1.25;contra.push(`Momentum erschöpft (${exhaustion.toFixed(1)}): nach starkem Lauf Reversal-Risiko erhöht`)}
 const liveRawCurrency=res.meta?.currency||rawCurrency(info),liveUnit=quoteCurrencyInfo(liveRawCurrency);markHealth(h,'Yahoo 1m Chart',true,'',started);return{...info,currency:liveUnit.majorCurrency||inferCurrency(info),quoteCurrencyRaw:liveRawCurrency,quotePriceScale:liveUnit.priceScale,quoteUnitNormalized:true,price:normalizeQuotePrice(price,liveRawCurrency),score,dayChange:day,momentum5:m5,momentum20:m20,momentumAcceleration5:accel5,momentumState,momentumBreakoutScore:breakoutScore,momentumExhaustionScore:exhaustion,momentumSellSignal,drawdownFrom20mHighPct:drawFromHigh,rsi:rr,volumeRatio:vr,newsScore:0,newsConfidence:0,newsSources:[],fresh,reasons:[...pro,...contra],pro,contra,headlines:[]}}catch(e){markHealth(h,'Yahoo 1m Chart',false,e,started);return null}}

async function yahooNews(c,h){const started=Date.now();try{const u=new URL('https://feeds.finance.yahoo.com/rss/2.0/headline');u.searchParams.set('s',c.symbol);u.searchParams.set('region','US');u.searchParams.set('lang','en-US');const r=await fetch(u,{headers:feedHeaders});if(!r.ok)throw new Error(`HTTP ${r.status}`);const items=parseFeed(await r.text(),12).map(x=>({...x,source:'Yahoo',weight:1}));markHealth(h,'Yahoo News',true,'',started);return items}catch(e){markHealth(h,'Yahoo News',false,e,started);return[]}}
async function googleNews(c,h){const started=Date.now();try{const u=new URL('https://news.google.com/rss/search');u.searchParams.set('q',`"${newsSearchName(c)}" when:2d`);u.searchParams.set('hl','de');u.searchParams.set('gl','DE');u.searchParams.set('ceid','DE:de');const r=await fetch(u,{headers:feedHeaders});if(!r.ok)throw new Error(`HTTP ${r.status}`);const items=parseFeed(await r.text(),12).map(x=>({...x,source:'Google News',weight:1.08}));markHealth(h,'Google News',true,'',started);return items}catch(e){markHealth(h,'Google News',false,e,started);return[]}}
async function publicFeed(source,url,h,weight=1,limit=50){const started=Date.now();try{const r=await fetch(url,{headers:feedHeaders,redirect:'follow'});if(!r.ok)throw new Error(`HTTP ${r.status}`);const items=parseFeed(await r.text(),limit).map(x=>({...x,source,weight}));if(!items.length)throw new Error('Feed ohne lesbare Meldungen');markHealth(h,source,true,'',started);return items}catch(e){markHealth(h,source,false,e,started);return[]}}
function companyWords(c){const legal=new Set(['inc','corp','corporation','company','co','plc','ag','se','sa','nv','ltd','limited','holdings','holding','group','registered','ordinary','shares','ord','shs']);return normalizeHeadline(c.name||c.symbol).split(' ').filter(w=>w.length>=4&&!legal.has(w))}
function matchesCompany(c,title){const t=normalizeHeadline(title),words=companyWords(c);if(!t)return false;if(words.length&&t.includes(words.slice(0,Math.min(2,words.length)).join(' ')))return true;if(words[0]?.length>=5&&t.split(' ').includes(words[0]))return true;const sym=String(c.symbol||'').split('.')[0].replace(/[^A-Z0-9]/gi,'').toLowerCase();return sym.length>=4&&new RegExp(`(^|\\s)${sym}(\\s|$)`,'i').test(t)}
function selectGlobal(items,c){return(items||[]).filter(x=>matchesCompany(c,x.title)).slice(0,10)}

function clusterNews(info,sets,calendar){const raw=[];for(const x of sets.flat()){if(!x?.title)continue;const age=newsTradingAgeHours(info,x.publishedAt,new Date(),calendar);if(age>NEWS_MAX_TRADING_AGE_HOURS)continue;raw.push({...x,tradingAge:age})}raw.sort((a,b)=>(Date.parse(b.publishedAt||0)||0)-(Date.parse(a.publishedAt||0)||0));const clusters=[];for(const item of raw){let c=clusters.find(g=>similarity(g.headline,item.title)>=.48);if(!c){c={headline:item.title,publishedAt:item.publishedAt,items:[],sources:new Set(),sentiments:[]};clusters.push(c)}c.items.push(item);c.sources.add(String(item.source||'News').split('/')[0]);c.sentiments.push(headlineSentiment(item.title));if((Date.parse(item.publishedAt||0)||0)>(Date.parse(c.publishedAt||0)||0)){c.headline=item.title;c.publishedAt=item.publishedAt}}
 let weighted=0,den=0;for(const c of clusters){const fresh=newsRecencyWeight(info,c.publishedAt,calendar);if(fresh<=0)continue;const base=c.sentiments.length?c.sentiments.reduce((a,b)=>a+b,0)/c.sentiments.length:0,confirm=Math.min(1.35,1+.08*Math.max(0,c.sources.size-1)+.03*Math.max(0,c.items.length-1)),official=c.sources.has('Börse Frankfurt')?1.18:1,weight=fresh*confirm*official;weighted+=base*weight;den+=weight;c.freshness=fresh;c.eventScore=base;c.confirmations=c.items.length;c.sourceCount=c.sources.size}
 const score=clamp(den?weighted/den:0,-2,2),sourceSet=new Set(raw.map(x=>String(x.source||'News').split('/')[0])),latest=clusters[0],latestWeight=latest?newsRecencyWeight(info,latest.publishedAt,calendar):0,confidence=clamp((clusters.length?0.22:0)+Math.min(.26,clusters.length*.045)+Math.min(.28,sourceSet.size*.1)+Math.min(.18,latestWeight*.1)+Math.min(.14,(latest?.sourceCount||0)*.04),0,1),freshImpact=Math.abs(score)*confidence*Math.max(.1,latestWeight);return{score,confidence,freshImpact,latestWeight,latestTradingAge:latest?newsTradingAgeHours(info,latest.publishedAt,new Date(),calendar):null,headlines:clusters.slice(0,8).map(x=>x.headline),latestAt:latest?.publishedAt||null,sources:[...sourceSet],clusterCount:clusters.length,confirmationCount:latest?.confirmations||0,items:clusters}}

async function quoteEvents(symbols,h){if(!symbols.length)return new Map();const started=Date.now();try{const u=new URL('https://query1.finance.yahoo.com/v7/finance/quote');u.searchParams.set('symbols',symbols.join(','));const r=await fetch(u,{headers});if(!r.ok)throw new Error(`HTTP ${r.status}`);const j=await r.json(),m=new Map();for(const q of j?.quoteResponse?.result||[]){const earn=q.earningsTimestampStart||q.earningsTimestamp||q.earningsCallTimestampStart||null,div=q.dividendDate||null;m.set(String(q.symbol||'').toUpperCase(),{earningsAt:earn?new Date(earn*1000).toISOString():null,dividendAt:div?new Date(div*1000).toISOString():null})}markHealth(h,'Yahoo Events',true,'',started);return m}catch(e){markHealth(h,'Yahoo Events',false,e,started);return new Map()}}
function eventRisk(ev){const now=Date.now(),items=[];if(ev?.earningsAt){const h=(Date.parse(ev.earningsAt)-now)/3600000;if(h>=0&&h<=24)items.push({level:'HIGH',text:`Quartalszahlen in ${h.toFixed(1)}h`});else if(h>24&&h<=72)items.push({level:'MEDIUM',text:`Quartalszahlen in ${(h/24).toFixed(1)} Tagen`})}if(ev?.dividendAt){const h=(Date.parse(ev.dividendAt)-now)/3600000;if(h>=0&&h<=36)items.push({level:'LOW',text:'Dividendentermin nahe'})}const level=items.some(x=>x.level==='HIGH')?'HIGH':items.some(x=>x.level==='MEDIUM')?'MEDIUM':items.length?'LOW':'NONE';return{level,text:items.map(x=>x.text).join(' · ')}}
function candidateConfidence(c){let x=.28+clamp(Math.abs(c.score)/10,0,.35)+clamp((c.volumeRatio-1)/4,0,.12)+clamp(c.newsConfidence*.18,0,.18);if(c.eventRisk==='HIGH')x-=.16;if(!c.fresh)x-=.3;return clamp(x,0,1)}
function rotate(pool,count,seed){if(!pool.length||!count)return[];const start=(seed*count)%pool.length,out=[];for(let i=0;i<Math.min(count,pool.length);i++)out.push(pool[(start+i)%pool.length]);return out}
function rotatingRadar(items){const minute=Math.floor(Date.now()/60000),priority=items.filter(x=>x.priority),regular=items.filter(x=>!x.priority),a=Math.min(Math.ceil(NEWS_RADAR_BATCH/2),priority.length),b=NEWS_RADAR_BATCH-a;return[...rotate(priority,a,minute),...rotate(regular,b,minute+17)]}
function newsPriorityTargets(items,limit){const shock=[...items].filter(x=>Math.abs(num(x?.dayChange))>=4||Math.abs(num(x?.momentum20))>=2).sort((a,b)=>Math.abs(num(b?.dayChange))-Math.abs(num(a?.dayChange))||Math.abs(num(b?.momentum20))-Math.abs(num(a?.momentum20))),out=[];for(const c of [...shock,...items]){if(c&&!out.some(x=>x.symbol===c.symbol)){out.push(c);if(out.length>=limit)break}}return out}
function newsSearchName(c){const words=companyWords(c),full=String(c?.name||c?.symbol||'').replace(/"/g,'').trim(),core=words.slice(0,3).join(' ');return core.length>=5?core:full}

function median(xs){const a=(xs||[]).filter(Number.isFinite).sort((a,b)=>a-b);if(!a.length)return 0;const m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2}
function coarseMarketBreadth(rows=[]){const a=(rows||[]).filter(x=>x?.fresh&&!x?.benchmark&&Number.isFinite(Number(x?.coarseMomentum)));const n=a.length;if(!n)return{source:'COARSE_OPEN_UNIVERSE',sampleCount:0,regime:'UNKNOWN',breadthUp20:.5,breadthUpDay:.5,median20:0,medianAccel:0};const up20=a.filter(x=>num(x.coarseMomentum)>.03).length/n,upDay=a.filter(x=>num(x.dayChange)>0).length/n,med20=median(a.map(x=>num(x.coarseMomentum))),medA=median(a.map(x=>num(x.momentumAcceleration)));let regime='MIXED';if(up20>=.64&&med20>.08)regime='BROAD_UP';else if(up20<=.34&&med20<-.08)regime='RISK_OFF';else if(med20>0&&medA<-.05)regime='REVERSAL_DOWN';else if(med20<0&&medA>.05)regime='REVERSAL_UP';else if(Math.abs(med20)<.10)regime='RANGE';return{source:'COARSE_OPEN_UNIVERSE',sampleCount:n,regime,breadthUp20:+up20.toFixed(3),breadthUpDay:+upDay.toFixed(3),median20:+med20.toFixed(3),medianAccel:+medA.toFixed(3)}}

export async function scanMarket(env,cfg,heldSymbols=[]){const h=health(),calendar=await loadCalendar(env),uni=await loadUniverse(env,cfg),allScan=[];for(const x of [...uni.items,...BENCHMARKS])if(!allScan.some(y=>y.symbol===x.symbol))allScan.push({...x,currency:inferCurrency(x)});const now=new Date(),states=allScan.map(x=>({item:x,state:marketOpen(x,now,calendar)})),openItems=states.filter(x=>x.state.open).map(x=>x.item),activeMarkets=[...new Set(states.filter(x=>x.state.open).map(x=>x.state.label))],newsOnly=openItems.filter(x=>!x.benchmark).length===0,coarse=[];for(const batch of chunks(openItems,SPARK_BATCH))coarse.push(...await sparkBatch(batch,h));const base=String(cfg.currency||'EUR').toUpperCase(),fx=await fxRates(coarse.map(x=>inferCurrency(x)),base,h);for(const x of coarse){x.currency=inferCurrency(x);x.fxRate=fx[x.currency]||1}
 const tradable=coarse.filter(x=>!x.benchmark),freshTradable=tradable.filter(x=>x.fresh),marketBreadth=coarseMarketBreadth(freshTradable),selected=selectBalancedDeepCandidates(freshTradable,DEEP_LIMIT,MOMENTUM_BREAKOUT_RESERVE);for(const sym of heldSymbols){const inf=allScan.find(x=>x.symbol===sym);if(inf&&marketOpen(inf,now,calendar).open&&!selected.some(x=>x.symbol===sym)&&selected.length<DEEP_LIMIT+18){const x=tradable.find(v=>v.symbol===sym)||inf;if(x)selected.push({...x,fxRate:fx[inferCurrency(x)]||1})}}
 const deep=(await mapLimit(selected,6,x=>deepChart(x,h))).filter(Boolean).sort((a,b)=>b.score-a.score);for(const c of deep){c.fxRate=fx[c.currency]||1}
 const eventTargets=[...new Set(deep.slice(0,12).map(x=>x.symbol).concat(heldSymbols))].slice(0,24),events=await quoteEvents(eventTargets,h);for(const c of deep){const er=eventRisk(events.get(c.symbol));c.eventRisk=er.level;c.eventText=er.text;if(er.level==='HIGH'){c.score-=1.1;c.contra.push(er.text)}else if(er.level==='MEDIUM'){c.score-=.35;c.contra.push(er.text)}}
 const deepNewsTargets=newsPriorityTargets(deep,NEWS_LIMIT);for(const c of deep.filter(x=>heldSymbols.includes(x.symbol)))if(!deepNewsTargets.some(x=>x.symbol===c.symbol)&&deepNewsTargets.length<NEWS_LIMIT+6)deepNewsTargets.push(c);const radarTargets=rotatingRadar(uni.items),allNewsTargets=[];for(const c of [...deepNewsTargets,...radarTargets])if(!allNewsTargets.some(x=>x.symbol===c.symbol))allNewsTargets.push(c);
 const yres=await mapLimit(allNewsTargets,6,x=>yahooNews(x,h)),ymap=new Map(allNewsTargets.map((x,i)=>[x.symbol,yres[i]||[]]));
 const enhanced=[];for(const c of (cfg?.disable_google_news?[]:(newsOnly?radarTargets.slice(0,4):[...newsPriorityTargets(deep,2),...radarTargets.filter(x=>x.priority).slice(0,2)])))if(c&&!enhanced.some(x=>x.symbol===c.symbol))enhanced.push(c);const googleRes=await mapLimit(enhanced,4,x=>googleNews(x,h)),googleMap=new Map(enhanced.map((x,i)=>[x.symbol,googleRes[i]||[]]));
 const globalSets=await Promise.all([
  publicFeed('Börse Frankfurt','https://api.boerse-frankfurt.de/v1/feeds/news.rss',h,1.18,60),
  publicFeed('FinanzNachrichten','https://www.finanznachrichten.de/rss-aktien-nachrichten',h,1.08,60),
  publicFeed('wallstreetONLINE','https://www.wallstreet-online.de/rss/nachrichten-aktien-indizes.xml',h,1.02,60),
  publicFeed('BörsenNews','https://www.boersennews.de/service/news.rss',h,1.0,60)
 ]);const globalItems=globalSets.flat(),nmap=new Map();for(const c of allNewsTargets)nmap.set(c.symbol,clusterNews(c,[ymap.get(c.symbol)||[],googleMap.get(c.symbol)||[],selectGlobal(globalItems,c)],calendar));
 for(const c of deep){const n=nmap.get(c.symbol)||clusterNews(c,[],calendar);c.newsScore=num(n.score);c.newsConfidence=num(n.confidence);c.newsSources=n.sources||[];c.headlines=n.headlines||[];c.newsTradingAgeHours=n.latestTradingAge;c.newsClusters=n.clusterCount;c.score+=c.newsScore*c.newsConfidence*n.latestWeight;if(c.newsScore>.25)c.pro.push(`News +${c.newsScore.toFixed(1)} · ${n.clusterCount} Ereigniscluster`);if(c.newsScore<-.25)c.contra.push(`News ${c.newsScore.toFixed(1)} · ${n.clusterCount} Ereigniscluster`);c.confidence=candidateConfidence(c);c.reasons=[...c.pro,...c.contra]}
 deep.sort((a,b)=>b.score-a.score);
 const newsRadar=radarTargets.map(c=>{const n=nmap.get(c.symbol)||clusterNews(c,[],calendar),score=num(n.score),tendency=score>.28?'BULLISH':score<-.28?'BEARISH':'NEUTRAL',state=marketOpen(c,now,calendar);return{symbol:c.symbol,name:c.name||c.symbol,type:c.type,theme:c.theme||null,score,confidence:n.confidence,freshImpact:n.freshImpact,latestWeight:n.latestWeight,tradingAgeHours:n.latestTradingAge,tendency,sourceCount:(n.sources||[]).length,sources:n.sources||[],clusterCount:n.clusterCount,confirmationCount:n.confirmationCount,headline:n.headlines?.[0]||'',headlines:n.headlines||[],newsAt:n.latestAt||null,waitingForOpen:!state.open&&(n.latestTradingAge??99)<.01,market:state.label}}).filter(x=>x.headline).sort((a,b)=>b.freshImpact-a.freshImpact||(Date.parse(b.newsAt||0)||0)-(Date.parse(a.newsAt||0)||0));
 const benchmarks=BENCHMARKS.map(b=>{const q=coarse.find(x=>x.symbol===b.symbol);return q?{symbol:b.symbol,name:b.name,price:q.price,fxRate:q.fxRate||1,currency:q.currency,fresh:q.fresh}:null}).filter(Boolean);
 return{universe:uni.items,generatedAt:uni.generatedAt,candidates:deep,newsRadar,benchmarks,marketBreadth,fxRates:fx,events:Object.fromEntries(events),calendarGeneratedAt:calendar?.generated_at||null,health:sourceHealthSummary(h),marketState:{mode:newsOnly?'NEWS_ONLY':'MARKET_AND_NEWS',activeMarkets,openSymbols:openItems.length,closedSymbols:allScan.length-openItems.length}}}
