import {DurableObject} from 'cloudflare:workers';
import {AI_MODEL,clamp,num,nowIso,riskParams} from './constants.js';
import {scanMarket,newsRecencyWeight} from './market-v3.js';
import {runReplay} from './replay.js';

const DEFAULT_FEE_FIXED=1,DEFAULT_FEE_PERCENT=0,DEFAULT_SLIPPAGE=.10,DEFAULT_LEVERAGED_SLIPPAGE=.20,DEFAULT_MAX_ROUNDTRIP_COST=3;
const posValue=(p,price=p.last_price,fx=p.last_fx)=>!p?.entry_price?num(p?.invested):num(p.invested)*(num(price)/num(p.entry_price))*(num(fx,1)/num(p.entry_fx,1));
function riskLimits(mode){if(mode==='vorsichtig')return{dailyLoss:1.5,leverPct:10,themePct:35,cooldownLosses:2,cooldownMin:90};if(mode==='offensiv')return{dailyLoss:4,leverPct:25,themePct:60,cooldownLosses:3,cooldownMin:45};return{dailyLoss:2.5,leverPct:15,themePct:45,cooldownLosses:2,cooldownMin:60}}

export class MarketPortfolio extends DurableObject{
 constructor(ctx,env){super(ctx,env);ctx.blockConcurrencyWhile(async()=>{this.ctx.storage.sql.exec(`
 CREATE TABLE IF NOT EXISTS config(id INTEGER PRIMARY KEY CHECK(id=1),running INTEGER NOT NULL DEFAULT 0,start_capital REAL NOT NULL DEFAULT 100,cash REAL NOT NULL DEFAULT 100,currency TEXT NOT NULL DEFAULT 'EUR',risk_mode TEXT NOT NULL DEFAULT 'offensiv',include_etfs INTEGER NOT NULL DEFAULT 1,include_leverage INTEGER NOT NULL DEFAULT 1,ai_enabled INTEGER NOT NULL DEFAULT 1,started_at TEXT,ends_at TEXT,last_scan TEXT,scan_count INTEGER NOT NULL DEFAULT 0,last_error TEXT,scan_lock_until INTEGER NOT NULL DEFAULT 0,universe_count INTEGER NOT NULL DEFAULT 0,universe_generated_at TEXT,calendar_generated_at TEXT,ai_last_summary TEXT,fee_fixed REAL NOT NULL DEFAULT 1,fee_percent REAL NOT NULL DEFAULT 0,total_fees REAL NOT NULL DEFAULT 0,slippage_percent REAL NOT NULL DEFAULT .10,leveraged_slippage_percent REAL NOT NULL DEFAULT .20,max_roundtrip_cost_percent REAL NOT NULL DEFAULT 3,news_tendency_score REAL,news_tendency_label TEXT,news_tendency_summary TEXT,news_radar_updated_at TEXT,market_mode TEXT NOT NULL DEFAULT 'NEWS_ONLY',active_markets TEXT,open_symbols INTEGER NOT NULL DEFAULT 0,closed_symbols INTEGER NOT NULL DEFAULT 0);
 INSERT OR IGNORE INTO config(id) VALUES(1);
 CREATE TABLE IF NOT EXISTS positions(symbol TEXT PRIMARY KEY,name TEXT,instrument_type TEXT NOT NULL,theme TEXT,leverage REAL NOT NULL DEFAULT 1,invested REAL NOT NULL,entry_fee REAL NOT NULL DEFAULT 0,entry_price REAL NOT NULL,last_price REAL NOT NULL,entry_fx REAL NOT NULL DEFAULT 1,last_fx REAL NOT NULL DEFAULT 1,currency TEXT,opened_at TEXT NOT NULL,score REAL,signal_confidence REAL NOT NULL DEFAULT 0);
 CREATE TABLE IF NOT EXISTS history(id INTEGER PRIMARY KEY AUTOINCREMENT,ts TEXT NOT NULL,end_ts TEXT,event_count INTEGER NOT NULL DEFAULT 1,start_scan INTEGER,end_scan INTEGER,action TEXT NOT NULL,symbol TEXT,name TEXT,instrument_type TEXT,amount REAL NOT NULL DEFAULT 0,fee REAL NOT NULL DEFAULT 0,trade_pnl REAL,cash_before REAL NOT NULL,cash_after REAL NOT NULL,equity REAL NOT NULL,total_pnl REAL NOT NULL,score REAL,reason TEXT);
 CREATE TABLE IF NOT EXISTS snapshots(id INTEGER PRIMARY KEY AUTOINCREMENT,ts TEXT NOT NULL,equity REAL NOT NULL,cash REAL NOT NULL);
 CREATE TABLE IF NOT EXISTS candidates(symbol TEXT PRIMARY KEY,name TEXT,instrument_type TEXT NOT NULL,theme TEXT,leverage REAL NOT NULL DEFAULT 1,price REAL NOT NULL,fx_rate REAL NOT NULL DEFAULT 1,currency TEXT,score REAL NOT NULL,confidence REAL NOT NULL DEFAULT 0,day_change REAL,momentum5 REAL,momentum20 REAL,rsi REAL,volume_ratio REAL,news_score REAL,fresh INTEGER NOT NULL,pro TEXT,contra TEXT,event_risk TEXT,event_text TEXT,reason TEXT,updated_at TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS news_radar(symbol TEXT PRIMARY KEY,name TEXT,instrument_type TEXT NOT NULL,theme TEXT,news_score REAL NOT NULL,confidence REAL NOT NULL DEFAULT 0,tendency TEXT NOT NULL,source_count INTEGER NOT NULL DEFAULT 0,sources TEXT,cluster_count INTEGER NOT NULL DEFAULT 0,confirmation_count INTEGER NOT NULL DEFAULT 0,trading_age_hours REAL,waiting_for_open INTEGER NOT NULL DEFAULT 0,market TEXT,headline TEXT NOT NULL,news_at TEXT,updated_at TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS benchmarks(symbol TEXT PRIMARY KEY,name TEXT,start_price REAL NOT NULL,last_price REAL NOT NULL,start_fx REAL NOT NULL DEFAULT 1,last_fx REAL NOT NULL DEFAULT 1,currency TEXT,started_at TEXT NOT NULL,updated_at TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS ai_log(id INTEGER PRIMARY KEY AUTOINCREMENT,ts TEXT NOT NULL,kind TEXT NOT NULL,symbol TEXT,title TEXT NOT NULL,message TEXT NOT NULL,confidence REAL,meta TEXT);
 CREATE TABLE IF NOT EXISTS source_health(source TEXT PRIMARY KEY,status TEXT NOT NULL,ok_count INTEGER NOT NULL DEFAULT 0,fail_count INTEGER NOT NULL DEFAULT 0,last_error TEXT,latency_ms REAL,updated_at TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS replay_results(id INTEGER PRIMARY KEY CHECK(id=1),updated_at TEXT NOT NULL,result_json TEXT NOT NULL);
 `);for(const [t,n,d] of [
 ['config','calendar_generated_at','TEXT'],['positions','theme','TEXT'],['positions','entry_fx','REAL NOT NULL DEFAULT 1'],['positions','last_fx','REAL NOT NULL DEFAULT 1'],['positions','currency','TEXT'],['positions','signal_confidence','REAL NOT NULL DEFAULT 0'],['history','trade_pnl','REAL'],['candidates','theme','TEXT'],['candidates','fx_rate','REAL NOT NULL DEFAULT 1'],['candidates','currency','TEXT'],['candidates','confidence','REAL NOT NULL DEFAULT 0'],['candidates','pro','TEXT'],['candidates','contra','TEXT'],['candidates','event_risk','TEXT'],['candidates','event_text','TEXT'],['news_radar','cluster_count','INTEGER NOT NULL DEFAULT 0'],['news_radar','confirmation_count','INTEGER NOT NULL DEFAULT 0'],['news_radar','trading_age_hours','REAL'],['news_radar','waiting_for_open','INTEGER NOT NULL DEFAULT 0'],['news_radar','market','TEXT']])this.ensureColumn(t,n,d)});}
 ensureColumn(t,n,d){const c=this.ctx.storage.sql.exec(`PRAGMA table_info(${t})`).toArray();if(!c.some(x=>x.name===n))this.ctx.storage.sql.exec(`ALTER TABLE ${t} ADD COLUMN ${n} ${d}`)}
 cfg(){return this.ctx.storage.sql.exec('SELECT * FROM config WHERE id=1').one()}
 positions(){return this.ctx.storage.sql.exec('SELECT * FROM positions ORDER BY opened_at').toArray()}
 equity(cash,ps=this.positions()){return num(cash)+ps.reduce((s,p)=>s+posValue(p),0)}
 clear(t){this.ctx.storage.sql.exec(`DELETE FROM ${t}`)}
 fee(n,c=this.cfg()){return Math.max(0,num(c.fee_fixed,DEFAULT_FEE_FIXED))+Math.max(0,num(c.fee_percent,DEFAULT_FEE_PERCENT))*Math.max(0,num(n))/100}
 slippage(type,c=this.cfg()){return type==='LEVERAGED_ETF'?Math.max(0,num(c.leveraged_slippage_percent,DEFAULT_LEVERAGED_SLIPPAGE)):Math.max(0,num(c.slippage_percent,DEFAULT_SLIPPAGE))}
 minimumOrder(type,c=this.cfg()){const slip=this.slippage(type,c),variable=2*Math.max(0,num(c.fee_percent))+2*slip,budget=Math.max(.5,num(c.max_roundtrip_cost_percent,DEFAULT_MAX_ROUNDTRIP_COST)),room=budget-variable;return room<=0?Infinity:2*Math.max(0,num(c.fee_fixed,DEFAULT_FEE_FIXED))*100/room}
 executionModel(c=this.cfg()){return{feeFixed:num(c.fee_fixed),feePercent:num(c.fee_percent),slippagePercent:num(c.slippage_percent),leveragedSlippagePercent:num(c.leveraged_slippage_percent),maxRoundtripCostPercent:num(c.max_roundtrip_cost_percent),minOrderNormal:this.minimumOrder('EQUITY',c),minOrderLeveraged:this.minimumOrder('LEVERAGED_ETF',c)}}
 record(action,{symbol='',name='',type='',amount=0,fee=0,tradePnl=null,cashBefore,cashAfter,equity,score=null,reason='',scanNo=null}){const c=this.cfg(),t=nowIso(),pl=equity-num(c.start_capital);if(action==='HALTEN'){const last=this.ctx.storage.sql.exec('SELECT id,action,start_scan,end_scan,event_count FROM history ORDER BY id DESC LIMIT 1').toArray()[0];if(last?.action==='HALTEN'){const start=last.start_scan??(scanNo?Math.max(1,scanNo-num(last.event_count,1)):null),end=scanNo??last.end_scan;this.ctx.storage.sql.exec('UPDATE history SET end_ts=?,event_count=COALESCE(event_count,1)+1,start_scan=?,end_scan=?,cash_after=?,equity=?,total_pnl=?,score=?,reason=? WHERE id=?',t,start,end,cashAfter,equity,pl,score,reason,last.id);return}}this.ctx.storage.sql.exec('INSERT INTO history(ts,end_ts,event_count,start_scan,end_scan,action,symbol,name,instrument_type,amount,fee,trade_pnl,cash_before,cash_after,equity,total_pnl,score,reason) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',t,action==='HALTEN'?t:null,1,scanNo,scanNo,action,symbol,name,type,amount,fee,tradePnl,cashBefore,cashAfter,equity,pl,score,reason)}
 logAI(kind,title,message,{symbol='',confidence=null,meta=null}={}){this.ctx.storage.sql.exec('INSERT INTO ai_log(ts,kind,symbol,title,message,confidence,meta) VALUES(?,?,?,?,?,?,?)',nowIso(),kind,symbol,title,String(message).slice(0,1000),confidence,meta?JSON.stringify(meta):null);this.ctx.storage.sql.exec('DELETE FROM ai_log WHERE id NOT IN (SELECT id FROM ai_log ORDER BY id DESC LIMIT 500)')}

 candidateRows(rows){this.clear('candidates');const t=nowIso();for(const c of rows.slice(0,35))this.ctx.storage.sql.exec('INSERT INTO candidates(symbol,name,instrument_type,theme,leverage,price,fx_rate,currency,score,confidence,day_change,momentum5,momentum20,rsi,volume_ratio,news_score,fresh,pro,contra,event_risk,event_text,reason,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',c.symbol,c.name||c.symbol,c.type,c.theme||null,num(c.leverage,1),c.price,num(c.fxRate,1),c.currency||null,c.score,num(c.confidence),c.dayChange,c.momentum5,c.momentum20,c.rsi,c.volumeRatio,c.newsScore,c.fresh?1:0,(c.pro||[]).join(' · ').slice(0,700),(c.contra||[]).join(' · ').slice(0,700),c.eventRisk||'NONE',c.eventText||'',(c.reasons||[]).join(' · ').slice(0,1000),t)}
 upsertNews(rows){const t=nowIso();for(const r of rows||[])this.ctx.storage.sql.exec(`INSERT INTO news_radar(symbol,name,instrument_type,theme,news_score,confidence,tendency,source_count,sources,cluster_count,confirmation_count,trading_age_hours,waiting_for_open,market,headline,news_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(symbol) DO UPDATE SET name=excluded.name,instrument_type=excluded.instrument_type,theme=excluded.theme,news_score=excluded.news_score,confidence=excluded.confidence,tendency=excluded.tendency,source_count=excluded.source_count,sources=excluded.sources,cluster_count=excluded.cluster_count,confirmation_count=excluded.confirmation_count,trading_age_hours=excluded.trading_age_hours,waiting_for_open=excluded.waiting_for_open,market=excluded.market,headline=excluded.headline,news_at=excluded.news_at,updated_at=excluded.updated_at`,r.symbol,r.name||r.symbol,r.type||'EQUITY',r.theme||null,num(r.score),num(r.confidence),r.tendency||'NEUTRAL',num(r.sourceCount),JSON.stringify(r.sources||[]),num(r.clusterCount),num(r.confirmationCount),r.tradingAgeHours==null?null:num(r.tradingAgeHours),r.waitingForOpen?1:0,r.market||null,String(r.headline||'').slice(0,700),r.newsAt||null,t)}
 newsTrend(){const rows=this.ctx.storage.sql.exec('SELECT * FROM news_radar ORDER BY COALESCE(news_at,updated_at) DESC LIMIT 140').toArray(),recent=rows.map(x=>({...x,freshness:newsRecencyWeight({symbol:x.symbol},x.news_at)})).filter(x=>x.freshness>0),active=recent.filter(x=>Math.abs(num(x.news_score))>=.08),weight=x=>Math.max(.15,num(x.confidence))*x.freshness,den=active.reduce((s,x)=>s+weight(x),0),score=den?active.reduce((s,x)=>s+num(x.news_score)*weight(x),0)/den:0,label=score>.18?'BULLISH':score<-.18?'BEARISH':'NEUTRAL';recent.sort((a,b)=>(Math.abs(num(b.news_score))*weight(b))-(Math.abs(num(a.news_score))*weight(a)));return{score,label,rows:recent.slice(0,60)}}
 upsertHealth(h){const t=nowIso();for(const [source,x] of Object.entries(h||{}))this.ctx.storage.sql.exec(`INSERT INTO source_health(source,status,ok_count,fail_count,last_error,latency_ms,updated_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT(source) DO UPDATE SET status=excluded.status,ok_count=excluded.ok_count,fail_count=excluded.fail_count,last_error=excluded.last_error,latency_ms=excluded.latency_ms,updated_at=excluded.updated_at`,source,x.status||'UNKNOWN',num(x.okCount),num(x.failCount),x.lastError||'',x.latencyMs==null?null:num(x.latencyMs),t)}
 updateBenchmarks(rows){const t=nowIso();for(const b of rows||[]){const old=this.ctx.storage.sql.exec('SELECT symbol FROM benchmarks WHERE symbol=?',b.symbol).toArray()[0];if(old)this.ctx.storage.sql.exec('UPDATE benchmarks SET last_price=?,last_fx=?,currency=?,updated_at=? WHERE symbol=?',b.price,num(b.fxRate,1),b.currency||null,t,b.symbol);else this.ctx.storage.sql.exec('INSERT INTO benchmarks(symbol,name,start_price,last_price,start_fx,last_fx,currency,started_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)',b.symbol,b.name||b.symbol,b.price,b.price,num(b.fxRate,1),num(b.fxRate,1),b.currency||null,t,t)}}
 benchmarkStatus(){const c=this.cfg();return this.ctx.storage.sql.exec('SELECT * FROM benchmarks ORDER BY symbol').toArray().map(b=>{const value=num(c.start_capital)*(num(b.last_price)/num(b.start_price))*(num(b.last_fx,1)/num(b.start_fx,1));return{...b,value,returnPct:num(c.start_capital)?(value/num(c.start_capital)-1)*100:0}})}

 riskState(c=this.cfg()){const eq=this.equity(c.cash),lim=riskLimits(c.risk_mode),midnight=new Date();midnight.setUTCHours(0,0,0,0);const first=this.ctx.storage.sql.exec('SELECT equity FROM snapshots WHERE ts>=? ORDER BY id ASC LIMIT 1',midnight.toISOString()).toArray()[0],dayStart=num(first?.equity,num(c.start_capital)),dailyPct=dayStart?(eq/dayStart-1)*100:0,ps=this.positions(),leverValue=ps.filter(p=>p.instrument_type==='LEVERAGED_ETF').reduce((s,p)=>s+posValue(p),0),theme={};for(const p of ps){const k=p.theme||'OTHER';theme[k]=(theme[k]||0)+posValue(p)}const sells=this.ctx.storage.sql.exec("SELECT ts,trade_pnl FROM history WHERE action='VERKAUF' AND trade_pnl IS NOT NULL ORDER BY id DESC LIMIT 6").toArray();let losses=0;for(const s of sells){if(num(s.trade_pnl)<0)losses++;else break}const lastLoss=sells[0]&&num(sells[0].trade_pnl)<0?Date.parse(sells[0].ts):0,cooldownUntil=losses>=lim.cooldownLosses&&lastLoss?lastLoss+lim.cooldownMin*60000:0;return{equity:eq,dailyPct,limits:lim,leverPct:eq?leverValue/eq*100:0,themePct:Object.fromEntries(Object.entries(theme).map(([k,v])=>[k,eq?v/eq*100:0])),consecutiveLosses:losses,cooldownUntil,cooldownActive:cooldownUntil>Date.now()}}
 riskCheck(c,amount,cfg=this.cfg()){const r=this.riskState(cfg),theme=c.theme||'OTHER';if(r.dailyPct<=-r.limits.dailyLoss)return{ok:false,reason:`Tagesverlust-Limit ${r.limits.dailyLoss.toFixed(1)}% erreicht`};if(r.cooldownActive)return{ok:false,reason:`Cooldown nach ${r.consecutiveLosses} Verlusttrades bis ${new Date(r.cooldownUntil).toLocaleTimeString('de-DE')}`};const eq=Math.max(1,r.equity),futureTheme=(r.themePct[theme]||0)+amount/eq*100;if(futureTheme>r.limits.themePct)return{ok:false,reason:`Themenlimit ${theme}: ${futureTheme.toFixed(0)}% > ${r.limits.themePct}%`};if(c.type==='LEVERAGED_ETF'&&r.leverPct+amount/eq*100>r.limits.leverPct)return{ok:false,reason:`Hebel-Limit ${r.limits.leverPct}%`};const same=this.positions().filter(p=>(p.theme||'OTHER')===theme).length;if(same>=2)return{ok:false,reason:`Bereits ${same} Positionen im Thema ${theme}`};if(c.eventRisk==='HIGH')return{ok:false,reason:`Event-Risiko hoch: ${c.eventText||'Termin nahe'}`};return{ok:true,reason:'Risikolimits frei'}}

 async aiPlan(cands,ps,cfg){if(!cfg.ai_enabled)return{summary:'KI deaktiviert',actions:[]};if(!cands.length)return{summary:'NEWS-ONLY bzw. keine frischen handelbaren Kurse – keine Orderentscheidung.',actions:[]};const model=this.executionModel(cfg),risk=this.riskState(cfg),data=cands.slice(0,9).map(x=>({symbol:x.symbol,type:x.type,theme:x.theme,score:+x.score.toFixed(2),confidence:+num(x.confidence).toFixed(2),day:+x.dayChange.toFixed(2),m5:+x.momentum5.toFixed(2),m20:+x.momentum20.toFixed(2),rsi:x.rsi==null?null:+x.rsi.toFixed(1),news:+x.newsScore.toFixed(2),newsConfidence:+num(x.newsConfidence).toFixed(2),eventRisk:x.eventRisk,pro:(x.pro||[]).slice(0,4),contra:(x.contra||[]).slice(0,4),headlines:(x.headlines||[]).slice(0,2)})),held=ps.map(p=>({symbol:p.symbol,type:p.instrument_type,theme:p.theme,invested:p.invested,pnlPct:+((posValue(p)/p.invested-1)*100).toFixed(2),score:p.score})),prompt=`PAPER-TRADING ONLY. Keine echten Orders. Gib nur kompaktes JSON. Beruecksichtige frische Kurse, News-Cluster/Quellen, Event-Risiko, FX, Kosten und harte Risikolimits. Keine versteckten Gedankengaenge ausgeben, nur kurze nachvollziehbare Begruendung. Kosten ${model.feeFixed.toFixed(2)} ${cfg.currency}/Seite, Slippage ${model.slippagePercent.toFixed(2)}% normal/${model.leveragedSlippagePercent.toFixed(2)}% Hebel. Risikostatus=${JSON.stringify(risk)}. JSON {"summary":"kurz","actions":[{"symbol":"TICKER","action":"BUY|SELL|HOLD","confidence":0.0,"allocation_pct":0,"reason":"1 Satz"}]}. BUY nur Kandidaten, SELL nur gehaltene Werte mit frischem Signal. Kandidaten=${JSON.stringify(data)} Gehalten=${JSON.stringify(held)}`;try{const r=await this.env.AI.run(AI_MODEL,{messages:[{role:'user',content:prompt}],max_completion_tokens:750}),t=String(r?.response||r?.result?.response||''),a=t.indexOf('{'),b=t.lastIndexOf('}');if(a<0||b<=a)throw new Error('kein JSON');const j=JSON.parse(t.slice(a,b+1));return{summary:String(j.summary||'KI-Plan').slice(0,500),actions:(Array.isArray(j.actions)?j.actions:[]).map(x=>({symbol:String(x.symbol||'').toUpperCase(),action:String(x.action||'HOLD').toUpperCase(),confidence:clamp(num(x.confidence),0,1),allocation_pct:clamp(num(x.allocation_pct),0,35),reason:String(x.reason||'').slice(0,350)})).filter(x=>['BUY','SELL','HOLD'].includes(x.action))}}catch(e){return{summary:`KI-Fallback: ${String(e.message||e).slice(0,160)}`,actions:[]}}}
 async aiNewsSummary(trend,cfg,scanCount){if(!trend.rows.length)return'Noch keine ausreichenden Nachrichten für eine Tendenz.';if(!cfg.ai_enabled)return`News-Tendenz ${trend.label}.`;if(cfg.news_tendency_summary&&scanCount%5!==0)return cfg.news_tendency_summary;const sample=trend.rows.slice(0,12).map(x=>({symbol:x.symbol,score:num(x.news_score),confidence:num(x.confidence),freshness:num(x.freshness),waitingForOpen:Boolean(x.waiting_for_open),sources:x.sources,headline:x.headline})),prompt=`PAPER-TRADING. Fasse in einem kurzen deutschen Satz zusammen. News, die waehrend geschlossener Boerse eintreffen, bleiben bis zur naechsten Oeffnung hochrelevant; Alter wird in Handelszeit bewertet. Mehrere bestaetigende Quellen und offizielle Meldungen staerker gewichten. Keine Handlungsempfehlung. Tendenz=${trend.label} Daten=${JSON.stringify(sample)}`;try{const r=await this.env.AI.run(AI_MODEL,{messages:[{role:'user',content:prompt}],max_completion_tokens:130});return String(r?.response||r?.result?.response||'').trim().slice(0,450)||`News-Tendenz ${trend.label}.`}catch{return`News-Tendenz ${trend.label}.`}}

 close(symbol,marketPrice,fxRate,score,reason){let p;try{p=this.ctx.storage.sql.exec('SELECT * FROM positions WHERE symbol=?',symbol).one()}catch{return false}const c=this.cfg(),slip=this.slippage(p.instrument_type,c),execPrice=num(marketPrice)*(1-slip/100),before=num(c.cash),gross=posValue(p,execPrice,num(fxRate,p.last_fx)),fee=this.fee(gross,c),net=Math.max(0,gross-fee),after=before+net,pl=net-num(p.invested)-num(p.entry_fee);this.ctx.storage.sql.exec('DELETE FROM positions WHERE symbol=?',symbol);this.ctx.storage.sql.exec('UPDATE config SET cash=?,total_fees=COALESCE(total_fees,0)+? WHERE id=1',after,fee);const eq=this.equity(after);this.record('VERKAUF',{symbol,name:p.name,type:p.instrument_type,amount:net,fee,tradePnl:pl,cashBefore:before,cashAfter:after,equity:eq,score,scanNo:num(c.scan_count)+1,reason:`${reason} · FX ${num(fxRate,1).toFixed(5)} · Gebühr ${fee.toFixed(2)} · Trade P/L netto ${pl>=0?'+':''}${pl.toFixed(2)} ${c.currency}`});this.logAI('TRADE','Verkauf ausgeführt',`${symbol}: ${reason}. Netto-P/L ${pl>=0?'+':''}${pl.toFixed(2)} ${c.currency}.`,{symbol,confidence:num(p.signal_confidence),meta:{tradePnl:pl}});return true}
 open(cand,pct,reason){const cfg=this.cfg(),rp=riskParams(cfg.risk_mode),ps=this.positions();if(ps.some(p=>p.symbol===cand.symbol)||ps.length>=rp.max)return false;const before=num(cfg.cash),reserve=num(cfg.start_capital)*rp.reserve,available=Math.max(0,before-reserve),isLever=cand.type==='LEVERAGED_ETF',basePct=isLever?Math.min(num(pct,rp.lever*100),rp.lever*100):Math.min(num(pct,rp.normal*100),35),minOrder=this.minimumOrder(cand.type,cfg);let amount=num(cfg.start_capital)*basePct/100;if(amount<minOrder){if(num(cfg.start_capital)<250&&!isLever)amount=minOrder;else return false}amount=Math.min(amount,available);if(amount<minOrder*.98||amount<1)return false;const risk=this.riskCheck(cand,amount,cfg);if(!risk.ok){this.logAI('RISK','Trade blockiert',`${cand.symbol}: ${risk.reason}.`,{symbol:cand.symbol,confidence:cand.confidence});return false}let fee=this.fee(amount,cfg);if(amount+fee>available){amount=Math.max(0,available-num(cfg.fee_fixed))/(1+Math.max(0,num(cfg.fee_percent))/100);fee=this.fee(amount,cfg)}if(amount<minOrder*.98||amount+fee>before)return false;const slip=this.slippage(cand.type,cfg),execPrice=num(cand.price)*(1+slip/100),after=before-amount-fee,fx=num(cand.fxRate,1);this.ctx.storage.sql.exec('INSERT INTO positions(symbol,name,instrument_type,theme,leverage,invested,entry_fee,entry_price,last_price,entry_fx,last_fx,currency,opened_at,score,signal_confidence) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',cand.symbol,cand.name||cand.symbol,cand.type,cand.theme||null,num(cand.leverage,1),amount,fee,execPrice,cand.price,fx,fx,cand.currency||null,nowIso(),cand.score,num(cand.confidence));this.ctx.storage.sql.exec('UPDATE config SET cash=?,total_fees=COALESCE(total_fees,0)+? WHERE id=1',after,fee);const eq=this.equity(after),rt=(2*fee/amount*100)+(2*num(cfg.fee_percent))+(2*slip);this.record('KAUF',{symbol:cand.symbol,name:cand.name,type:cand.type,amount:-(amount+fee),fee,cashBefore:before,cashAfter:after,equity:eq,score:cand.score,scanNo:num(cfg.scan_count)+1,reason:`${reason} · Order ${amount.toFixed(2)} ${cfg.currency} · FX ${fx.toFixed(5)} · Roundtrip-Kosten ~${rt.toFixed(2)}%`});this.logAI('TRADE','Kauf ausgeführt',`${cand.symbol}: ${reason}. Pro: ${(cand.pro||[]).slice(0,2).join(', ')||'–'}. Contra: ${(cand.contra||[]).slice(0,2).join(', ')||'–'}.`,{symbol:cand.symbol,confidence:num(cand.confidence),meta:{score:cand.score,amount,theme:cand.theme}});return true}

 statistics(){const c=this.cfg(),ps=this.positions(),sells=this.ctx.storage.sql.exec("SELECT symbol,name,trade_pnl,ts FROM history WHERE action='VERKAUF' AND trade_pnl IS NOT NULL ORDER BY id").toArray(),wins=sells.filter(x=>num(x.trade_pnl)>0),losses=sells.filter(x=>num(x.trade_pnl)<0),realized=sells.reduce((a,x)=>a+num(x.trade_pnl),0),unrealized=ps.reduce((a,p)=>a+(posValue(p)-num(p.invested)-num(p.entry_fee)),0),avgWin=wins.length?wins.reduce((a,x)=>a+num(x.trade_pnl),0)/wins.length:0,avgLoss=losses.length?losses.reduce((a,x)=>a+num(x.trade_pnl),0)/losses.length:0,grossWin=wins.reduce((a,x)=>a+num(x.trade_pnl),0),grossLoss=Math.abs(losses.reduce((a,x)=>a+num(x.trade_pnl),0)),snaps=this.ctx.storage.sql.exec('SELECT equity FROM snapshots ORDER BY id').toArray();let peak=0,maxDD=0;for(const x of snaps){const e=num(x.equity);peak=Math.max(peak,e);if(peak>0)maxDD=Math.min(maxDD,(e/peak-1)*100)}const best=[...sells].sort((a,b)=>num(b.trade_pnl)-num(a.trade_pnl))[0]||null,worst=[...sells].sort((a,b)=>num(a.trade_pnl)-num(b.trade_pnl))[0]||null;return{closedTrades:sells.length,winRate:sells.length?wins.length/sells.length*100:0,realizedPnl:realized,unrealizedPnl:unrealized,avgWin,avgLoss,profitFactor:grossLoss?grossWin/grossLoss:grossWin>0?99:0,maxDrawdownPct:maxDD,best,worst,totalFees:num(c.total_fees)}}

 async scan(){let cfg=this.cfg();if(!cfg.running)return{ok:true,skipped:'not-running'};const now=Date.now();if(num(cfg.scan_lock_until)>now)return{ok:true,skipped:'busy'};this.ctx.storage.sql.exec('UPDATE config SET scan_lock_until=? WHERE id=1',now+55000);try{cfg=this.cfg();if(cfg.ends_at&&now>=Date.parse(cfg.ends_at)){for(const p of this.positions())this.close(p.symbol,p.last_price,p.last_fx,p.score,'Planspiel-Zeitraum beendet (letzter bekannter Kurs)');this.ctx.storage.sql.exec('UPDATE config SET running=0,scan_lock_until=0 WHERE id=1');this.logAI('SYSTEM','Planspiel beendet','Laufzeit erreicht; offene Positionen wurden mit dem letzten verfügbaren Planspielkurs geschlossen.');return{ok:true,finished:true}}
 const held=this.positions(),m=await scanMarket(this.env,cfg,held.map(p=>p.symbol)),ms=m.marketState||{mode:'NEWS_ONLY',activeMarkets:[],openSymbols:0,closedSymbols:m.universe.length};this.ctx.storage.sql.exec('UPDATE config SET universe_count=?,universe_generated_at=?,calendar_generated_at=?,market_mode=?,active_markets=?,open_symbols=?,closed_symbols=? WHERE id=1',m.universe.length,m.generatedAt||null,m.calendarGeneratedAt||null,ms.mode,JSON.stringify(ms.activeMarkets||[]),num(ms.openSymbols),num(ms.closedSymbols));this.candidateRows(m.candidates);this.upsertNews(m.newsRadar);this.upsertHealth(m.health);this.updateBenchmarks(m.benchmarks);for(const p of held){const c=m.candidates.find(x=>x.symbol===p.symbol);if(c)this.ctx.storage.sql.exec('UPDATE positions SET last_price=?,last_fx=?,score=?,signal_confidence=? WHERE symbol=?',c.price,num(c.fxRate,1),c.score,num(c.confidence),p.symbol)}
 const oldTrend=cfg.news_tendency_label,trend=this.newsTrend(),nextScan=num(cfg.scan_count)+1,newsSummary=await this.aiNewsSummary(trend,cfg,nextScan);this.ctx.storage.sql.exec('UPDATE config SET news_tendency_score=?,news_tendency_label=?,news_tendency_summary=?,news_radar_updated_at=? WHERE id=1',trend.score,trend.label,newsSummary,nowIso());if(oldTrend&&oldTrend!==trend.label)this.logAI('NEWS','News-Tendenz geändert',`${oldTrend} → ${trend.label} (${trend.score.toFixed(2)}).`,{confidence:Math.min(1,Math.abs(trend.score))});
 if(ms.mode==='NEWS_ONLY'){cfg=this.cfg();const eq=this.equity(cfg.cash),t=nowIso(),summary=`NEWS-ONLY: Märkte geschlossen. News bleiben bis zur jeweiligen nächsten Börsenöffnung handelszeitlich frisch. Tendenz ${trend.label} (${trend.score.toFixed(2)}).`;this.ctx.storage.sql.exec('UPDATE config SET ai_last_summary=? WHERE id=1',summary);this.record('HALTEN',{cashBefore:num(cfg.cash),cashAfter:num(cfg.cash),equity:eq,scanNo:nextScan,reason:summary});this.ctx.storage.sql.exec('INSERT INTO snapshots(ts,equity,cash) VALUES(?,?,?)',t,eq,num(cfg.cash));this.ctx.storage.sql.exec('UPDATE config SET last_scan=?,scan_count=?,last_error=NULL,scan_lock_until=0 WHERE id=1',t,nextScan);return{ok:true,equity:eq,actions:0,marketMode:ms.mode,newsTrend:trend.label}}
 const current=this.positions(),ai=await this.aiPlan(m.candidates,current,cfg),am=new Map(ai.actions.map(x=>[x.symbol,x]));this.ctx.storage.sql.exec('UPDATE config SET ai_last_summary=? WHERE id=1',ai.summary);const rp=riskParams(cfg.risk_mode);let actions=0;for(const p of this.positions()){const c=m.candidates.find(x=>x.symbol===p.symbol);if(!c||!c.fresh)continue;const pnl=posValue({...p,last_price:c.price,last_fx:c.fxRate})/num(p.invested)-1,a=am.get(p.symbol);let why=null,stop=p.instrument_type==='LEVERAGED_ETF'?Math.max(rp.stop,-.028):rp.stop,take=p.instrument_type==='LEVERAGED_ETF'?Math.min(rp.take,.06):rp.take;if(pnl<=stop)why=`virtueller Stop ${(pnl*100).toFixed(2)}%`;else if(pnl>=take)why=`virtuelles Gewinnziel ${(pnl*100).toFixed(2)}%`;else if(c.score<0)why=`Signal gefallen auf ${c.score.toFixed(2)}`;else if(a?.action==='SELL'&&a.confidence>=.55)why=`KI SELL ${Math.round(a.confidence*100)}%: ${a.reason}`;if(why&&this.close(p.symbol,c.price,c.fxRate,c.score,why))actions++}
 cfg=this.cfg();const existing=this.positions(),slots=rp.max-existing.length,buy=[];for(const c of m.candidates){if(!c.fresh||existing.some(p=>p.symbol===c.symbol))continue;const a=am.get(c.symbol);if(a?.action==='BUY'&&a.confidence>=.55&&c.confidence>=.48&&c.score>=rp.entry-.8)buy.push({c,a,k:c.score+a.confidence+c.confidence})}if(!buy.length)for(const c of m.candidates.filter(x=>x.fresh&&x.confidence>=.55&&x.score>=rp.entry&&!existing.some(p=>p.symbol===x.symbol)).slice(0,slots))buy.push({c,a:null,k:c.score+c.confidence});buy.sort((a,b)=>b.k-a.k);for(const x of buy.slice(0,slots)){const why=x.a?`KI BUY ${Math.round(x.a.confidence*100)}%: ${x.a.reason}`:`Regel-Fallback: Score ${x.c.score.toFixed(2)}, Konfidenz ${Math.round(x.c.confidence*100)}%`;if(this.open(x.c,x.a?.allocation_pct,why))actions++}
 cfg=this.cfg();const eq=this.equity(cfg.cash),count=num(cfg.scan_count)+1,t=nowIso();if(!actions){const top=m.candidates[0],reason=top?`Kein Trade. Bestes Signal ${top.symbol}: Score ${top.score.toFixed(2)}, Konfidenz ${Math.round(top.confidence*100)}%.`:`Keine frischen handelbaren Signale.`;this.record('HALTEN',{cashBefore:num(cfg.cash),cashAfter:num(cfg.cash),equity:eq,reason,scanNo:count});if(top&&count%10===0&&top.confidence>=.55)this.logAI('IDEA','Beobachtungskandidat',`${top.symbol}: ${reason} Pro: ${(top.pro||[]).slice(0,2).join(', ')||'–'}; Contra: ${(top.contra||[]).slice(0,2).join(', ')||'–'}.`,{symbol:top.symbol,confidence:top.confidence})}
 this.ctx.storage.sql.exec('INSERT INTO snapshots(ts,equity,cash) VALUES(?,?,?)',t,eq,num(cfg.cash));this.ctx.storage.sql.exec('DELETE FROM snapshots WHERE id NOT IN (SELECT id FROM snapshots ORDER BY id DESC LIMIT 3000)');this.ctx.storage.sql.exec('UPDATE config SET last_scan=?,scan_count=?,last_error=NULL,scan_lock_until=0 WHERE id=1',t,count);return{ok:true,equity:eq,actions,marketMode:ms.mode,newsTrend:trend.label,ai:ai.summary}
 }catch(e){const msg=String(e?.message||e).slice(0,900),c=this.cfg(),eq=this.equity(c.cash);this.record('FEHLER',{cashBefore:num(c.cash),cashAfter:num(c.cash),equity:eq,reason:`Scan fehlgeschlagen: ${msg}`,scanNo:num(c.scan_count)+1});this.logAI('ERROR','Scan-Fehler',msg);this.ctx.storage.sql.exec('UPDATE config SET last_error=?,scan_lock_until=0 WHERE id=1',msg);return{ok:false,error:msg}}}

 async replay(){const result=await runReplay({riskMode:this.cfg().risk_mode});this.ctx.storage.sql.exec('INSERT INTO replay_results(id,updated_at,result_json) VALUES(1,?,?) ON CONFLICT(id) DO UPDATE SET updated_at=excluded.updated_at,result_json=excluded.result_json',nowIso(),JSON.stringify(result));this.logAI('REPLAY','Historischer Replay abgeschlossen',`${result.window}: ${result.trades} Trades, Trefferquote ${result.winRate.toFixed(1)}%, mittlere Rendite ${result.avgReturnPct>=0?'+':''}${result.avgReturnPct.toFixed(2)}%.`);return result}
 async status(){const c=this.cfg(),ps=this.positions(),eq=this.equity(c.cash),rr=this.ctx.storage.sql.exec('SELECT updated_at,result_json FROM replay_results WHERE id=1').toArray()[0];return{config:c,executionModel:this.executionModel(c),risk:this.riskState(c),statistics:this.statistics(),equity:eq,pnl:eq-num(c.start_capital),pnl_pct:num(c.start_capital)?(eq/num(c.start_capital)-1)*100:0,positions:ps,history:this.ctx.storage.sql.exec('SELECT * FROM history ORDER BY id DESC LIMIT 220').toArray(),snapshots:this.ctx.storage.sql.exec('SELECT * FROM snapshots ORDER BY id DESC LIMIT 500').toArray().reverse(),candidates:this.ctx.storage.sql.exec('SELECT * FROM candidates ORDER BY score DESC LIMIT 35').toArray(),newsRadar:this.ctx.storage.sql.exec('SELECT * FROM news_radar ORDER BY COALESCE(news_at,updated_at) DESC LIMIT 50').toArray(),benchmarks:this.benchmarkStatus(),aiLog:this.ctx.storage.sql.exec('SELECT * FROM ai_log ORDER BY id DESC LIMIT 100').toArray(),sourceHealth:this.ctx.storage.sql.exec('SELECT * FROM source_health ORDER BY source').toArray(),replay:rr?{updated_at:rr.updated_at,...JSON.parse(rr.result_json)}:null}}
 async start(o={}){const cap=clamp(num(o.startCapital,100),1,10000000),v=clamp(Math.floor(num(o.durationValue,7)),1,10000),u=String(o.durationUnit||'days'),mins=v*(u==='hours'?60:u==='weeks'?10080:1440),risk=['vorsichtig','ausgewogen','offensiv'].includes(o.riskMode)?o.riskMode:'offensiv',feeFixed=clamp(num(o.feeFixed,DEFAULT_FEE_FIXED),0,100000),feePercent=clamp(num(o.feePercent,DEFAULT_FEE_PERCENT),0,100),now=Date.now();for(const t of ['positions','history','snapshots','candidates','news_radar','benchmarks','ai_log','source_health'])this.clear(t);this.ctx.storage.sql.exec(`UPDATE config SET running=1,start_capital=?,cash=?,currency=?,risk_mode=?,include_etfs=?,include_leverage=?,ai_enabled=?,fee_fixed=?,fee_percent=?,slippage_percent=?,leveraged_slippage_percent=?,max_roundtrip_cost_percent=?,total_fees=0,started_at=?,ends_at=?,last_scan=NULL,scan_count=0,last_error=NULL,scan_lock_until=0,ai_last_summary=NULL,news_tendency_score=NULL,news_tendency_label=NULL,news_tendency_summary=NULL,news_radar_updated_at=NULL,market_mode='NEWS_ONLY',active_markets='[]',open_symbols=0,closed_symbols=0 WHERE id=1`,cap,cap,String(o.currency||'EUR').toUpperCase(),risk,o.includeEtfs===false?0:1,o.includeLeverage===false?0:1,o.aiEnabled===false?0:1,feeFixed,feePercent,DEFAULT_SLIPPAGE,DEFAULT_LEVERAGED_SLIPPAGE,DEFAULT_MAX_ROUNDTRIP_COST,new Date(now).toISOString(),new Date(now+mins*60000).toISOString());this.logAI('SYSTEM','Planspiel gestartet',`${cap.toFixed(2)} ${String(o.currency||'EUR').toUpperCase()}, ${v} ${u}, Risiko ${risk}. FX, Gebühren, Event- und Risikolimits aktiv.`);return{ok:true}}
 async stop(){const c=this.cfg(),eq=this.equity(c.cash);this.ctx.storage.sql.exec('UPDATE config SET running=0,scan_lock_until=0 WHERE id=1');this.record('STOP',{cashBefore:num(c.cash),cashAfter:num(c.cash),equity:eq,reason:'Planspiel manuell gestoppt.'});this.logAI('SYSTEM','Planspiel gestoppt','Automatische Scans wurden manuell angehalten.');return{ok:true}}
 async reset(){for(const t of ['positions','history','snapshots','candidates','news_radar','benchmarks','ai_log','source_health','replay_results'])this.clear(t);this.ctx.storage.sql.exec("UPDATE config SET running=0,start_capital=100,cash=100,currency='EUR',risk_mode='offensiv',include_etfs=1,include_leverage=1,ai_enabled=1,fee_fixed=1,fee_percent=0,slippage_percent=.10,leveraged_slippage_percent=.20,max_roundtrip_cost_percent=3,total_fees=0,started_at=NULL,ends_at=NULL,last_scan=NULL,scan_count=0,last_error=NULL,scan_lock_until=0,ai_last_summary=NULL,news_tendency_score=NULL,news_tendency_label=NULL,news_tendency_summary=NULL,news_radar_updated_at=NULL,market_mode='NEWS_ONLY',active_markets='[]',open_symbols=0,closed_symbols=0 WHERE id=1");return{ok:true}}
}
