import {riskParams} from './constants.js';

const SYMBOLS=['SPY','QQQ','NVDA','MSFT','GOOGL','PLTR','RHM.DE','HAG.DE','VWCE.DE','EXXT.DE'];
const headers={'accept':'application/json','user-agent':'Mozilla/5.0'};
function ema(a,p){if(a.length<p)return null;const k=2/(p+1);let e=a.slice(0,p).reduce((x,y)=>x+y,0)/p;for(const v of a.slice(p))e=v*k+e*(1-k);return e}
function rsi(a,p=14){if(a.length<p+1)return null;let g=0,l=0;const s=a.slice(-(p+1));for(let i=1;i<s.length;i++){const d=s[i]-s[i-1];d>0?g+=d:l-=d}if(!l)return 100;const rs=(g/p)/(l/p);return 100-100/(1+rs)}
function scoreAt(cl){if(cl.length<22)return null;const p=cl.at(-1),e9=ema(cl,9),e21=ema(cl,21),rr=rsi(cl),m5=(p/cl.at(-2)-1)*100,m20=(p/cl.at(-5)-1)*100;let s=0;if(e9&&e21&&e9>e21)s+=1.7;else s-=1;if(e21&&p>e21)s+=.8;else s-=.6;if(rr>=48&&rr<=68)s+=1;else if(rr>=78)s-=1.5;else if(rr<=32)s-=.8;if(m5>.18)s+=.8;else if(m5<-.25)s-=.9;if(m20>.5)s+=1.2;else if(m20<-.5)s-=1.2;return{s,price:p}}
async function chart(symbol){const u=new URL(`https://query1.finance.yahoo.com/v8/finance/chart/${encodeURIComponent(symbol)}`);u.searchParams.set('range','5d');u.searchParams.set('interval','5m');u.searchParams.set('includePrePost','false');const r=await fetch(u,{headers});if(!r.ok)throw new Error(`${symbol}: HTTP ${r.status}`);const j=await r.json(),x=j?.chart?.result?.[0];if(!x)throw new Error(`${symbol}: keine Daten`);const q=x?.indicators?.quote?.[0]||{},ts=x.timestamp||[],cl=q.close||[],rows=[];for(let i=0;i<Math.min(ts.length,cl.length);i++)if(Number.isFinite(Number(cl[i])))rows.push({ts:ts[i]*1000,close:Number(cl[i])});return rows}
async function mapLimit(items,n,fn){const out=new Array(items.length);let i=0;await Promise.all(Array.from({length:n},async()=>{while(true){const k=i++;if(k>=items.length)return;try{out[k]=await fn(items[k])}catch(e){out[k]={error:String(e.message||e)}}}}));return out}
function replayOne(symbol,rows,mode,feeFixed=1,slip=.1){const rp=riskParams(mode),cl=[],trades=[];let pos=null,cash=100;for(let i=0;i<rows.length;i++){cl.push(rows[i].close);if(cl.length<22)continue;const sig=scoreAt(cl);if(!sig)continue;if(!pos&&sig.s>=rp.entry){const fee=feeFixed,amount=Math.max(0,cash-fee),entry=sig.price*(1+slip/100);if(amount>0){pos={entry,amount,fee,at:rows[i].ts};cash=0}}else if(pos){const pnl=sig.price/pos.entry-1;if(pnl<=rp.stop||pnl>=rp.take||sig.s<0||i===rows.length-1){const exit=sig.price*(1-slip/100),gross=pos.amount*(exit/pos.entry),net=Math.max(0,gross-feeFixed),tradePnl=net-pos.amount-pos.fee;trades.push({pnl:tradePnl,retPct:pos.amount?tradePnl/pos.amount*100:0,openedAt:pos.at,closedAt:rows[i].ts});cash=net;pos=null}}}return{symbol,endValue:cash,returnPct:cash-100,trades}}
export async function runReplay({riskMode='ausgewogen'}={}){const started=new Date().toISOString(),data=await mapLimit(SYMBOLS,4,async s=>({symbol:s,rows:await chart(s)})),results=[];for(const d of data){if(!d||d.error)continue;results.push(replayOne(d.symbol,d.rows,riskMode))}const trades=results.flatMap(x=>x.trades.map(t=>({...t,symbol:x.symbol}))),wins=trades.filter(x=>x.pnl>0),loss=trades.filter(x=>x.pnl<0),avgReturn=results.length?results.reduce((s,x)=>s+x.returnPct,0)/results.length:0,grossWin=wins.reduce((s,x)=>s+x.pnl,0),grossLoss=Math.abs(loss.reduce((s,x)=>s+x.pnl,0)),best=[...trades].sort((a,b)=>b.pnl-a.pnl)[0]||null,worst=[...trades].sort((a,b)=>a.pnl-b.pnl)[0]||null;return{startedAt:started,finishedAt:new Date().toISOString(),window:'5d / 5m',symbols:results.length,trades:trades.length,winRate:trades.length?wins.length/trades.length*100:0,avgReturnPct:avgReturn,profitFactor:grossLoss?grossWin/grossLoss:grossWin>0?99:0,best,worst,results:results.map(x=>({symbol:x.symbol,returnPct:+x.returnPct.toFixed(2),trades:x.trades.length})),note:'Replay verwendet pro Balken nur bis dahin bekannte Kursdaten; er ist eine Diagnose des technischen Regelkerns, keine Zukunftsprognose.'}}
